import image1 from "../../assets/Images/ImageDataBase/Dairy/image1.jpg";
import image2 from "../../assets/Images/ImageDataBase/Dairy/image2.jpg";
import image3 from "../../assets/Images/ImageDataBase/Dairy/image3.jpg";
import image4 from "../../assets/Images/ImageDataBase/Dairy/image4.jpg";
import image5 from "../../assets/Images/ImageDataBase/Dairy/image5.jpg";
import image6 from "../../assets/Images/ImageDataBase/Dairy/image6.jpg";
import image7 from "../../assets/Images/ImageDataBase/Dairy/image7.jpg";
import image8 from "../../assets/Images/ImageDataBase/Dairy/image8.jpg";
import image9 from "../../assets/Images/ImageDataBase/Dairy/image9.jpg";
import image10 from "../../assets/Images/ImageDataBase/Dairy/image10.jpg";
import image11 from "../../assets/Images/ImageDataBase/Dairy/image11.jpg";
import image12 from "../../assets/Images/ImageDataBase/Dairy/image12.jpg";
import image13 from "../../assets/Images/ImageDataBase/Dairy/image13.jpg";
import image14 from "../../assets/Images/ImageDataBase/Dairy/image14.jpg";
import image15 from "../../assets/Images/ImageDataBase/Dairy/image15.jpg";
import image16 from "../../assets/Images/ImageDataBase/Dairy/image16.jpg";
import image17 from "../../assets/Images/ImageDataBase/Dairy/image17.jpg";
import image18 from "../../assets/Images/ImageDataBase/Dairy/image18.jpg";
import image19 from "../../assets/Images/ImageDataBase/Dairy/image19.jpg";
import image20 from "../../assets/Images/ImageDataBase/Dairy/image20.jpg";
import image21 from "../../assets/Images/ImageDataBase/Dairy/image21.jpg";
import image22 from "../../assets/Images/ImageDataBase/Dairy/image22.jpg";
import image23 from "../../assets/Images/ImageDataBase/Dairy/image23.jpg";
import image24 from "../../assets/Images/ImageDataBase/Dairy/image24.jpg";
import image25 from "../../assets/Images/ImageDataBase/Dairy/image25.jpg";
import image26 from "../../assets/Images/ImageDataBase/Dairy/image26.jpg";
import image27 from "../../assets/Images/ImageDataBase/Dairy/image27.jpg";
import image28 from "../../assets/Images/ImageDataBase/Dairy/image28.jpg";
import image29 from "../../assets/Images/ImageDataBase/Dairy/image29.jpg";
import image30 from "../../assets/Images/ImageDataBase/Dairy/image30.jpg";
import image31 from "../../assets/Images/ImageDataBase/Dairy/image31.jpg";
import image32 from "../../assets/Images/ImageDataBase/Dairy/image32.jpg";
import image33 from "../../assets/Images/ImageDataBase/Dairy/image33.jpg";
import image34 from "../../assets/Images/ImageDataBase/Dairy/image34.jpg";
import image35 from "../../assets/Images/ImageDataBase/Dairy/image35.jpg";
import image36 from "../../assets/Images/ImageDataBase/Dairy/image36.jpg";
import image37 from "../../assets/Images/ImageDataBase/Dairy/image37.jpg";
import image38 from "../../assets/Images/ImageDataBase/Dairy/image38.jpg";
import image39 from "../../assets/Images/ImageDataBase/Dairy/image39.jpg";
import image40 from "../../assets/Images/ImageDataBase/Dairy/image40.jpg";
import image41 from "../../assets/Images/ImageDataBase/Dairy/image41.jpg";
import image42 from "../../assets/Images/ImageDataBase/Dairy/image42.jpg";
import image43 from "../../assets/Images/ImageDataBase/Dairy/image43.jpg";
import image44 from "../../assets/Images/ImageDataBase/Dairy/image44.jpg";

export const DataBaseDairy = [
  {
    id: 3,
    name: "لبنیات",
    categories: ["شیر","پنیر","ماست","دوغ",],
    Dairy: [
      {
        id: 1,
        category: "شیر",
        image: image1,
        title: "شیر پرچرب مدت دار کاله ۱ لیتر",
        Weight: "1 لیتر",
        priceReduction: "",
        Discount: "",
        Price: "30,000",
        Brand: "کاله",
        Seller: "هایپر استار",
        ProductFeatures: [
          {
            id: 47,
            type: "ساده",
            skinType: "",
            effect: "",
            Durability: "",
            dis: "پر چرب",
          },
        ],
      },
      {
        id: 2,
        category: "شیر",
        image: image2,
        title: "شیر کم چرب مدت دار کاله ۱ لیتری",
        Weight: "1 لیتر",
        priceReduction: "",
        Discount: "",
        Price: "29,000",
        Brand: "کاله",
        Seller: "هایپر استار",
        ProductFeatures: [
          {
            id: 48,
            type: "ساده",
            skinType: "",
            effect: "",
            Durability: "",
            dis: "کم چرب",
          },
        ],
      },
      {
        id: 3,
        category: "شیر",
        image: image3,
        title: "شیر پرچرب مدت دار هراز ۱ لیتر",
        Weight: "1 لیتر",
        priceReduction: "29,800",
        Discount: "25%",
        Price: "22,350",
        Brand: "هراز",
        Seller: "هایپر استار",
        ProductFeatures: [
          {
            id: 49,
            type: "",
            skinType: "",
            effect: "",
            Durability: "",
            dis: "پر چرب",
          },
        ],
      },
      {
        id: 4,
        category: "شیر",
        image: image4,
        title: "شیر کم چرب مدت دار هراز ۱ لیتر",
        Weight: "1 لیتر",
        priceReduction: "28,900",
        Discount: "20%",
        Price: "23,120",
        Brand: "هراز",
        Seller: "هایپر استار",
        ProductFeatures: [
          {
            id: 50,
            type: "",
            skinType: "",
            effect: "",
            Durability: "",
            dis: "کم چرب",
          },
        ],
      },
      {
        id: 5,
        category: "شیر",
        image: image5,
        title: "بسته ۱۲ عددی شیر کاکائو و شیر موز نیم چرب مدت دار حاوی ویتامین A و D دنت ۱۲۵ میلی لیتری",
        Weight: "125 میلی لیتر",
        priceReduction: "",
        Discount: "",
        Price: "87,600",
        Brand: "دنت",
        Seller: "هایپر استار",
        ProductFeatures: [
          {
            id: 51,
            type: "۸ عدد شیر کاکائو",
            skinType: "",
            effect: "",
            Durability: "",
            dis: "۴ عدد شیر موز",
          },
        ],
      },
      {
        id: 6,
        category: "شیر",
        image: image6,
        title: "سوپر شیر کم چرب مدت دار حاوی ویتامین D و A روزانه ۱ لیتری",
        Weight: " 1لیتری ",
        priceReduction: "33,000",
        Discount: "12%",
        Price: "29,040",
        Brand: "روزانه",
        Seller: "هایپر استار",
        ProductFeatures: [
          {
            id: 50,
            type: "ساده",
            skinType: "",
            effect: "",
            Durability: "",
            dis: "کم چرب",
          },
        ],
      },
      {
        id: 7,
        category: "شیر",
        image: image7,
        title: "شیر موز کم چرب مدت دار هراز ۲۰۰ میلی لیتری",
        Weight: "200 میلی لیتر",
        priceReduction: "11,400",
        Discount: "14%",
        Price: "9,804",
        Brand: "هراز",
        Seller: "هایپر استار",
        ProductFeatures: [
          {
            id: 52,
            type: "",
            skinType: "",
            effect: "",
            Durability: "",
            dis: "",
          },
        ],
      },
      {
        id: 8,
        category: "شیر",
        image: image8,
        title: "شیر کاکائو نیم چرب مدت دار حاوی ویتامین D و A دنت ۱۲۵ میلی لیتری",
        Weight: "",
        priceReduction: "",
        Discount: "",
        Price: "7,300",
        Brand: "دنت",
        Seller: "هایپر استار",
        ProductFeatures: [
          {
            id: 53,
            type: "کاکائو",
            skinType: "",
            effect: "",
            Durability: "",
            dis: "",
          },
        ],
      },
      {
        id: 9,
        category: "شیر",
        image: image9,
        title: "شیر پرچرب مدت دار پگاه ۱ لیتر",
        Weight: "1 لیتر",
        priceReduction: "",
        Discount: "",
        Price: "30,000",
        Brand: "پگاه",
        Seller: "هایپر استار",
        ProductFeatures: [
          {
            id: 54,
            type: "",
            skinType: "",
            effect: "",
            Durability: "",
            dis: "",
          },
        ],
      },
      {
        id: 10,
        category: "شیر",
        image: image10,
        title: "شیر زیرو مدت دار بدون لاکتوز کاله ۱ لیتری",
        Weight: "1 لیتری",
        priceReduction: "",
        Discount: "",
        Price: "31,000",
        Brand: "کاله",
        Seller: "هایپر استار",
        ProductFeatures: [
          {
            id: 50,
            type: "ساده",
            skinType: "",
            effect: "",
            Durability: "",
            dis: "کم چرب",
          },
        ],
      },
      {
        id: 11,
        category: "شیر",
        image: image11,
        title: "شیر نیم چرب مدت دار پاک ۲۰۰ میلی لیتری",
        Weight: "200 میلی لیتری",
        priceReduction: "",
        Discount: "",
        Price: "9,000",
        Brand: "پاک",
        Seller: "هایپر استار",
        ProductFeatures: [
          {
            id: 55,
            type: "ساده",
            skinType: "",
            effect: "",
            Durability: "",
            dis: "نیم چرب",
          },
        ],
      },
      {
        id: 12,
        category: "پنیر",
        image: image12,
        title: "پنیر لبنه کالین ۳۰۰ گرم",
        Weight: "300 گرم",
        priceReduction: "",
        Discount: "",
        Price: "35,000",
        Brand: "کالین",
        Seller: "هایپر استار",
        ProductFeatures: [
          {
            id: 56,
            type: "",
            skinType: "",
            effect: "",
            Durability: "",
            dis: "",
          },
        ],
      },
      {
        id: 13,
        category: "پنیر",
        image: image13,
        title: " پنیر چدار ورقه ای کالین ۱۸۰ گرمی",
        Weight: "180 گرمی",
        priceReduction: "55,500",
        Discount: "28%",
        Price: "39,960",
        Brand: "کاله",
        Seller: "هایپر استار",
        ProductFeatures: [
          {
            id: 57,
            type: "ورقه ای",
            skinType: "",
            effect: "",
            Durability: "",
            dis: "چدار",
          },
        ],
      },
      {
        id: 14,
        category: "پنیر",
        image: image14,
        title: "پنیر سفید نیم چرب دوشه هراز ۴۰۰ گرمی",
        Weight: "400 گرمی",
        priceReduction: "39,800",
        Discount: "25%",
        Price: "29,850",
        Brand: "هراز",
        Seller: "هایپر استار",
        ProductFeatures: [
          {
            id: 58,
            type: "",
            skinType: "",
            effect: "",
            Durability: "",
            dis: "",
          },
        ],
      },
      {
        id: 15,
        category: "پنیر",
        image: image15,
        title: "پنیر سفید کم چرب روزانه ۵۱۵ گرمی",
        Weight: "515 گرمی",
        priceReduction: "61,000",
        Discount: "19%",
        Price: "49,410",
        Brand: "روزانه",
        Seller: "هایپر استار",
        ProductFeatures: [
          {
            id: 59,
            type: "پنیر سفید ",
            skinType: "",
            effect: "",
            Durability: "",
            dis: "قالبی",
          },
        ],
      },
      {
        id: 16,
        category: "پنیر",
        image: image16,
        title: "پنیر ماسکارپونه پرچرب کاله ۲۰۰ گرم",
        Weight: "200 گرم",
        priceReduction: "32,500",
        Discount: "19%",
        Price: "26,325",
        Brand: "کاله",
        Seller: "هایپر استار",
        ProductFeatures: [
          {
            id: 60,
            type: "پنیر سفید ",
            skinType: "",
            effect: "",
            Durability: "",
            dis: "قالبی",
          },
        ],
      },
      {
        id: 17,
        category: "پنیر",
        image: image17,
        title: "پنیر سفید نیم چرب روزانه ۳۴۰ گرمی",
        Weight: "340 گرمی",
        priceReduction: "45,000",
        Discount: "19%",
        Price: "36,450",
        Brand: "روزانه",
        Seller: "هایپر استار",
        ProductFeatures: [
          {
            id: 61,
            type: "پنیر سفید ",
            skinType: "",
            effect: "",
            Durability: "",
            dis: "قالبی",
          },
        ],
      },
      {
        id: 18,
        category: "پنیر",
        image: image18,
        title: "پنیر دیپ چدار کالین ۱۰۰ گرمی",
        Weight: "100 گرمی",
        priceReduction: "",
        Discount: "",
        Price: "26,000",
        Brand: "کالین",
        Seller: "هایپر استار",
        ProductFeatures: [
          {
            id: 62,
            type: "پنیر چدار",
            skinType: "",
            effect: "",
            Durability: "",
            dis: "قالبی",
          },
        ],
      },
      {
        id: 19,
        category: "پنیر",
        image: image19,
        title: "پنیر پارمسان و قارچ ورقه ای کالین ۱۸۰ گرمی",
        Weight: "180 گرمی",
        priceReduction: "55,500",
        Discount: "28%",
        Price: "39,960",
        Brand: "کالین",
        Seller: "هایپر استار",
        ProductFeatures: [
          {
            id: 63,
            type: "",
            skinType: "",
            effect: "",
            Durability: "",
            dis: "",
          },
        ],
      },
      {
        id: 20,
        category: "پنیر",
        image: image20,
        title: "پنیر موزارلا رنده شده ۲۰۲ ۱ کیلوگرمی",
        Weight: "1202 گیلو گرمی",
        priceReduction: "200,300",
        Discount: "20%",
        Price: "160,240",
        Brand: "202",
        Seller: "هایپر استار",
        ProductFeatures: [
          {
            id: 64,
            type: "پنیر پیتزا",
            skinType: "",
            effect: "",
            Durability: "",
            dis: "رنده شده",
          },
        ],
      },
      {
        id: 21,
        category: "پنیر",
        image: image21,
        title: "پنیر تاپینگ مخلوط رنده شده پروسس موزارلا و چدار کالین ۱ کیلوگرمی",
        Weight: "1 گیلو گرمی",
        priceReduction: "249,000",
        Discount: "11%",
        Price: "221,610",
        Brand: "کالین",
        Seller: "هایپر استار",
        ProductFeatures: [
          {
            id: 65,
            type: "",
            skinType: "",
            effect: "",
            Durability: "",
            dis: "",
          },
        ],
      },
      {
        id: 22,
        category: "پنیر",
        image: image22,
        title: "پنیر خامه ای پرچرب شکلاتی آلیما ۲۵۰ گرم",
        Weight: "250 گرمی",
        priceReduction: "35,000",
        Discount: "19%",
        Price: "28,350",
        Brand: "آلیما",
        Seller: "هایپر استار",
        ProductFeatures: [
          {
            id: 66,
            type: "",
            skinType: "",
            effect: "",
            Durability: "",
            dis: "",
          },
        ],
      },
      {
        id: 23,
        category: "ماست",
        image: image23,
        title: "ماست همزده میوه ای آلوئه‌ورا با میوه های جنگلی کم چرب کاله ۴۵۰ گرم",
        Weight: "450 گرمی",
        priceReduction: "43,000",
        Discount: "15%",
        Price: "36,550",
        Brand: "کاله",
        Seller: "هایپر استار",
        ProductFeatures: [
          {
            id: 67,
            type: "طعم دار",
            skinType: "",
            effect: "",
            Durability: "",
            dis: "آلوئه‌ورا",
          },
        ],
      },
      {
        id: 24,
        category: "ماست",
        image: image24,
        title: "ماست پرچرب پروبیوتیک هراز ۱.۸ کیلوگرمی",
        Weight: "۱.۸ کیلوگرمی",
        priceReduction: "56,900",
        Discount: "25%",
        Price: "42,675",
        Brand: "هراز",
        Seller: "هایپر استار",
        ProductFeatures: [
          {
            id: 68,
            type: "",
            skinType: "",
            effect: "",
            Durability: "",
            dis: "",
          },
        ],
      },
      {
        id: 25,
        category: "ماست",
        image: image25,
        title: "ماست همزده میوه ای کم چرب کاله ۴۵۰ گرم",
        Weight: " ۴۵۰ گرم",
        priceReduction: "43,000",
        Discount: "15%",
        Price: "36,550",
        Brand: "کاله",
        Seller: "هایپر استار",
        ProductFeatures: [
          {
            id: 69,
            type: "توت فرنگی",
            skinType: "",
            effect: "",
            Durability: "",
            dis: "طعم دار",
          },
        ],
      },
      {
        id: 26,
        category: "ماست",
        image: image26,
        title: "ماست کم چرب حاوی ویتامین D۳ کاله ۱.۹ کیلوگرمی",
        Weight: "۱.۹ کیلوگرمی",
        priceReduction: "49,900",
        Discount: "25%",
        Price: "37,425",
        Brand: "کاله",
        Seller: "هایپر استار",
        ProductFeatures: [
          {
            id: 70,
            type: "",
            skinType: "",
            effect: "",
            Durability: "",
            dis: "",
          },
        ],
      },
      {
        id: 27,
        category: "ماست",
        image: image27,
        title: "ماست چکیده موسیر کم چرب می ماس ۵۰۰ گرم",
        Weight: " ۵۰۰ گرم",
        priceReduction: "35,000",
        Discount: "11%",
        Price: "31,150",
        Brand: "می ماس",
        Seller: "هایپر استار",
        ProductFeatures: [
          {
            id: 71,
            type: "طعم دار",
            skinType: "",
            effect: "",
            Durability: "",
            dis: "",
          },
        ],
      },
      {
        id: 28,
        category: "ماست",
        image: image28,
        title: "ماست همزده میوه ای نیم چرب کاله ۱۲۵ گرمی",
        Weight: "۱۲۵ گرمی",
        priceReduction: "12,600",
        Discount: "25%",
        Price: "9,450",
        Brand: "کاله",
        Seller: "هایپر استار",
        ProductFeatures: [
          {
            id: 72,
            type: "طعم دار",
            skinType: "",
            effect: "",
            Durability: "",
            dis: "",
          },
        ],
      },
      {
        id: 29,
        category: "ماست",
        image: image29,
        title: "ماست همزده کم چرب سون کاله ۲.۲ کیلوگرمی",
        Weight: "۲.۲ کیلوگرمی",
        priceReduction: "85,000",
        Discount: "20%",
        Price: "68,000",
        Brand: "کاله",
        Seller: "هایپر استار",
        ProductFeatures: [
          {
            id: 73,
            type: "کم چرب",
            skinType: "",
            effect: "",
            Durability: "",
            dis: "",
          },
        ],
      },
      {
        id: 30,
        category: "ماست",
        image: image30,
        title: "ماست چکیده پرچرب پروبیوتیک کفیر ناری کاله ۴۰۰ گرم",
        Weight: "۴۰۰ گرم",
        priceReduction: "37,000",
        Discount: "20%",
        Price: "29,600",
        Brand: "کاله",
        Seller: "هایپر استار",
        ProductFeatures: [
          {
            id: 74,
            type: "",
            skinType: "",
            effect: "",
            Durability: "",
            dis: "",
          },
        ],
      },
      {
        id: 31,
        category: "ماست",
        image: image31,
        title: "ماست میوه ای توت فرنگی نیم چرب کاله ۱۲۵ گرم",
        Weight: "۱۲۵ گرم",
        priceReduction: "12,600",
        Discount: "11%",
        Price: "11,214",
        Brand: "کاله",
        Seller: "هایپر استار",
        ProductFeatures: [
          {
            id: 75,
            type: "توت فرنگی",
            skinType: "",
            effect: "",
            Durability: "",
            dis: "",
          },
        ],
      },
      {
        id: 32,
        category: "ماست",
        image: image32,
        title: "ماست پرچرب حاوی ویتامین D۳ کاله ۱.۹ کیلوگرمی",
        Weight: "۱.۹ کیلوگرمی",
        priceReduction: "55,000",
        Discount: "25%",
        Price: "41,250",
        Brand: "کاله",
        Seller: "هایپر استار",
        ProductFeatures: [
          {
            id: 76,
            type: "",
            skinType: "",
            effect: "",
            Durability: "",
            dis: "",
          },
        ],
      },
      {
        id: 33,
        category: "ماست",
        image: image33,
        title: "ماست چکیده موسیر کم چرب می ماس ۲۵۰ گرمی",
        Weight: "۲۵۰ گرمی",
        priceReduction: "19,000",
        Discount: "11%",
        Price: "16,910",
        Brand: "کاله",
        Seller: "هایپر استار",
        ProductFeatures: [
          {
            id: 77,
            type: "طعم دار",
            skinType: "",
            effect: "",
            Durability: "",
            dis: "موسیر",
          },
        ],
      },
      {
        id: 34,
        category: "دوغ",
        image: image34,
        title: "دوغ بدون گاز پونه هراز ۱.۵ لیتری",
        Weight: "۱.۵ لیتری",
        priceReduction: "26,900",
        Discount: "18%",
        Price: "22,058",
        Brand: "هراز",
        Seller: "هایپر استار",
        ProductFeatures: [
          {
            id: 78,
            type: "بدون گاز",
            skinType: "",
            effect: "",
            Durability: "",
            dis: "با سبزی معطر",
          },
        ],
      },
      {
        id: 35,
        category: "دوغ",
        image: image35,
        title: "دوغ گازدار هراز ۱.۵ لیتری",
        Weight: "۱.۵ لیتری",
        priceReduction: "27,900",
        Discount: "20%",
        Price: "22,320",
        Brand: " هراز ",
        Seller: "هایپر استار",
        ProductFeatures: [
          {
            id: 79,
            type: "گاز دار",
            skinType: "",
            effect: "",
            Durability: "",
            dis: "",
          },
        ],
      },
      {
        id: 36,
        category: "دوغ",
        image: image36,
        title: "دوغ بدون گاز ترش گلپر هراز ۱.۵ لیتری",
        Weight: "۱.۵ لیتری",
        priceReduction: "26,900",
        Discount: "20%",
        Price: "21,520",
        Brand: "هراز",
        Seller: "هایپر استار",
        ProductFeatures: [
          {
            id: 80,
            type: "بدون گاز",
            skinType: "",
            effect: "",
            Durability: "",
            dis: "با سبزی معطر",
          },
        ],
      },
      {
        id: 37,
        category: "دوغ",
        image: image37,
        title: "دوغ بدون گاز گرمادیده کاله ۱.۵ لیتری",
        Weight: "۱.۵ لیتری",
        priceReduction: "27,000",
        Discount: "25%",
        Price: "20,250",
        Brand: "کاله",
        Seller: "هایپر استار",
        ProductFeatures: [
          {
            id: 81,
            type: "بدون گاز",
            skinType: "",
            effect: "",
            Durability: "",
            dis: "",
          },
        ],
      },
      {
        id: 38,
        category: "دوغ",
        image: image38,
        title: "دوغ بدون گاز سبزیجات دلال گرمادیده هراز ۱.۵ لیتری",
        Weight: "۱.۵ لیتری",
        priceReduction: "29,800",
        Discount: "15%",
        Price: "25,330",
        Brand: "هراز ",
        Seller: "هایپر استار",
        ProductFeatures: [
          {
            id: 82,
            type: "بدون گاز",
            skinType: "",
            effect: "",
            Durability: "",
            dis: "با سبزی معطر",
          },
        ],
      },
      {
        id: 39,
        category: "دوغ",
        image: image39,
        title: "دوغ بدون گاز هشت گیاه عالیس ۱.۵ لیتری",
        Weight: "۱.۵ لیتری",
        priceReduction: "27,000",
        Discount: "9%",
        Price: "24,570",
        Brand: " عالیس ",
        Seller: "هایپر استار",
        ProductFeatures: [
          {
            id: 83,
            type: "بدون گاز",
            skinType: "",
            effect: "",
            Durability: "",
            dis: "با سبزی معطر",
          },
        ],
      },
      {
        id: 40,
        category: "دوغ",
        image: image40,
        title: "دوغ بدون گاز نعنایی گرمادیده صباح ۱.۵ لیتری",
        Weight: "۱.۵ لیتری",
        priceReduction: "26,000",
        Discount: "23%",
        Price: "20,020",
        Brand: "صباح",
        Seller: "هایپر استار",
        ProductFeatures: [
          {
            id: 84,
            type: "بدون گاز",
            skinType: "",
            effect: "",
            Durability: "",
            dis: "",
          },
        ],
      },
      {
        id: 41,
        category: "دوغ",
        image: image41,
        title: "دوغ بدون گاز نعنایی هراز ۹۰۰ میلی لیتری",
        Weight: "۹۰۰ میلی لیتری",
        priceReduction: "",
        Discount: "",
        Price: "10,900",
        Brand: "هراز",
        Seller: "هایپر استار",
        ProductFeatures: [
          {
            id: 85,
            type: "بدون گاز",
            skinType: "",
            effect: "",
            Durability: "",
            dis: "با سبزی معطر",
          },
        ],
      },
      {
        id: 42,
        category: "دوغ",
        image: image42,
        title: "دوغ بدون گاز نعنا و پونه کاله ۹۰۰ گرمی",
        Weight: "۹۰۰ گرمی",
        priceReduction: "",
        Discount: "",
        Price: "12,000",
        Brand: "کاله",
        Seller: "هایپر استار",
        ProductFeatures: [
          {
            id: 86,
            type: "بدون گاز",
            skinType: "",
            effect: "",
            Durability: "",
            dis: "با سبزی معطر",
          },
        ],
      },
      {
        id: 43,
        category: "دوغ",
        image: image43,
        title: "دوغ بدون گاز گلپر هراز ۹۰۰ میلی لیتری",
        Weight: "۹۰۰ میلی لیتری",
        priceReduction: "",
        Discount: "",
        Price: "10,900",
        Brand: "کاله",
        Seller: "هایپر استار",
        ProductFeatures: [
          {
            id: 87,
            type: "بدون گاز",
            skinType: "",
            effect: "",
            Durability: "",
            dis: "با سبزی معطر",
          },
        ],
      },
      {
        id: 44,
        category: "دوغ",
        image: image44,
        title: "دوغ بدون گاز نعنایی عالیس ۲۷۵ میلی لیتری",
        Weight: "۲۷۵ میلی لیتری",
        priceReduction: "",
        Discount: "",
        Price: "7,500",
        Brand: "عالیس",
        Seller: "هایپر استار",
        ProductFeatures: [
          {
            id: 88,
            type: "بدون گاز",
            skinType: "",
            effect: "",
            Durability: "",
            dis: "با سبزی معطر",
          },
        ],
      },


    ],
  },
];
