import image1 from "../../assets/Images/ImageDataBase/Drink/image1.jpg";
import image2 from "../../assets/Images/ImageDataBase/Drink/image2.jpg";
import image3 from "../../assets/Images/ImageDataBase/Drink/image3.jpg";
import image4 from "../../assets/Images/ImageDataBase/Drink/image4.jpg";
import image5 from "../../assets/Images/ImageDataBase/Drink/image5.jpg";
import image6 from "../../assets/Images/ImageDataBase/Drink/image6.jpg";
import image7 from "../../assets/Images/ImageDataBase/Drink/image7.jpg";
import image8 from "../../assets/Images/ImageDataBase/Drink/image8.jpg";
import image9 from "../../assets/Images/ImageDataBase/Drink/image9.jpg";
import image10 from "../../assets/Images/ImageDataBase/Drink/image10.jpg";
import image11 from "../../assets/Images/ImageDataBase/Drink/image11.jpg";
import image12 from "../../assets/Images/ImageDataBase/Drink/image12.jpg";
import image13 from "../../assets/Images/ImageDataBase/Drink/image13.jpg";
import image14 from "../../assets/Images/ImageDataBase/Drink/image14.jpg";
import image15 from "../../assets/Images/ImageDataBase/Drink/image15.jpg";
import image16 from "../../assets/Images/ImageDataBase/Drink/image16.jpg";
import image17 from "../../assets/Images/ImageDataBase/Drink/image17.jpg";
import image18 from "../../assets/Images/ImageDataBase/Drink/image18.jpg";
import image19 from "../../assets/Images/ImageDataBase/Drink/image19.jpg";
import image20 from "../../assets/Images/ImageDataBase/Drink/image20.jpg";
import image21 from "../../assets/Images/ImageDataBase/Drink/image21.jpg";
import image22 from "../../assets/Images/ImageDataBase/Drink/image22.jpg";
import image23 from "../../assets/Images/ImageDataBase/Drink/image23.jpg";
import image24 from "../../assets/Images/ImageDataBase/Drink/image24.jpg";
import image25 from "../../assets/Images/ImageDataBase/Drink/image25.jpg";
import image26 from "../../assets/Images/ImageDataBase/Drink/image26.jpg";
import image27 from "../../assets/Images/ImageDataBase/Drink/image27.jpg";
import image28 from "../../assets/Images/ImageDataBase/Drink/image28.jpg";
import image29 from "../../assets/Images/ImageDataBase/Drink/image29.jpg";
import image30 from "../../assets/Images/ImageDataBase/Drink/image30.jpg";
import image31 from "../../assets/Images/ImageDataBase/Drink/image31.jpg";
import image32 from "../../assets/Images/ImageDataBase/Drink/image32.jpg";
import image33 from "../../assets/Images/ImageDataBase/Drink/image33.jpg";
import image34 from "../../assets/Images/ImageDataBase/Drink/image34.jpg";
import image35 from "../../assets/Images/ImageDataBase/Drink/image35.jpg";
import image36 from "../../assets/Images/ImageDataBase/Drink/image36.jpg";
import image37 from "../../assets/Images/ImageDataBase/Drink/image37.jpg";
import image38 from "../../assets/Images/ImageDataBase/Drink/image38.jpg";
import image39 from "../../assets/Images/ImageDataBase/Drink/image39.jpg";
import image40 from "../../assets/Images/ImageDataBase/Drink/image40.jpg";
import image41 from "../../assets/Images/ImageDataBase/Drink/image41.jpg";
import image42 from "../../assets/Images/ImageDataBase/Drink/image42.jpg";
import image43 from "../../assets/Images/ImageDataBase/Drink/image43.jpg";
import image44 from "../../assets/Images/ImageDataBase/Drink/image44.jpg";

export const DataBaseDrink = [
  {
    id: 3,
    name: "نوشیدنی",
    categories: ["نوشابه","ماءالشعیر","آبمیوه","چای و دمنوش",],
    Drink: [
      {
        id: 1,
        category: "نوشابه",
        image: image1,
        title: "بسته ۶ عددی نوشابه کولا کوکاکولا ۱.۵ لیتری",
        Weight: " ۱.۵ لیتری",
        priceReduction: "107,060",
        Discount: "11%",
        Price: "95,284",
        Brand: "کوکاکولا",
        Seller: "هایپر استار",
        ProductFeatures: [
          {
            id: 47,
            type: "کولا",
            skinType: "بطری",
            effect: "",
            Durability: "",
            dis: "خانواده",
          },
        ],
      },
      {
        id: 2,
        category: "نوشابه",
        image: image2,
        title:"بسته ۶ عددی نوشابه کولا کوکاکولا ۱.۵ لیتری" ,
        Weight: " ۱.۵ لیتری",
        priceReduction: "1.7,070",
        Discount: "25%",
        Price: "80,303",
        Brand: "سون آپ",
        Seller: "هایپر استار",
        ProductFeatures: [
          {
            id: 48,
            type: "لیمویی",
            skinType: "بطری",
            effect: "",
            Durability: "",
            dis: "خانواده",
          },
        ],
      },
      {
        id: 3,
        category: "نوشابه",
        image: image3,
        title: "بسته ۶ عددی نوشابه پرتقالی میرندا ۱.۵ لیتری",
        Weight: "۱.۵ لیتری",
        priceReduction: "107,070",
        Discount: "25%",
        Price: "80,303",
        Brand: "میرندا",
        Seller: "هایپر استار",
        ProductFeatures: [
          {
            id: 49,
            type: "پرتغالی",
            skinType: "بطری",
            effect: "",
            Durability: "",
            dis: "خانواده",
          },
        ],
      },
      {
        id: 4,
        category: "نوشابه",
        image: image4,
        title: "بسته ۱۲ عددی نوشابه کولا کوکاکولا ۲۵۰ میلی لیتری",
        Weight: "۲۵۰ میلی لیتری",
        priceReduction: "",
        Discount: "",
        Price: "120,000",
        Brand: "کوکاکولا",
        Seller: "هایپر استار",
        ProductFeatures: [
          {
            id: 50,
            type: "کولا",
            skinType: "بطری",
            effect: "",
            Durability: "",
            dis: "یکنفره",
          },
        ],
      },
      {
        id: 5,
        category: "نوشابه",
        image: image5,
        title: "نوشابه کولا کوکاکولا ۱.۵ لیتری",
        Weight: "۱.۵ لیتری",
        priceReduction: "17,845",
        Discount: "10%",
        Price: "16,061",
        Brand: "کوکاکولا",
        Seller: "هایپر استار",
        ProductFeatures: [
          {
            id: 51,
            type: "کولا",
            skinType: "بطری",
            effect: "",
            Durability: "",
            dis: "خانواده",
          },
        ],
      },
      {
        id: 6,
        category: "نوشابه",
        image: image6,
        title: "بسته ۶ عددی نوشابه پرتقالی فانتا ۱.۵ لیتری",
        Weight: "  ۱.۵ لیتری",
        priceReduction: "107,060",
        Discount: "6%",
        Price: "100,637",
        Brand: "فانتا",
        Seller: "هایپر استار",
        ProductFeatures: [
          {
            id: 50,
            type: "پرتغالی",
            skinType: "بطری",
            effect: "",
            Durability: "",
            dis: "خانواده",
          },
        ],
      },
      {
        id: 7,
        category: "نوشابه",
        image: image7,
        title: "بسته ۶ عددی نوشابه لیمویی فانتا ۱.۵ لیتری",
        Weight: "۱.۵ لیتری",
        priceReduction: "",
        Discount: "",
        Price: "107,060",
        Brand: "فانتا",
        Seller: "هایپر استار",
        ProductFeatures: [
          {
            id: 52,
            type: "لیمویی",
            skinType: "",
            effect: "",
            Durability: "",
            dis: "",
          },
        ],
      },
      {
        id: 8,
        category: "نوشابه",
        image: image8,
        title: "نوشابه لیمویی سون آپ ۱.۵ لیتری",
        Weight: "۱.۵ لیتری",
        priceReduction: "17,845",
        Discount: "20%",
        Price: "14,276",
        Brand: "سون آپ",
        Seller: "هایپر استار",
        ProductFeatures: [
          {
            id: 53,
            type: "لیمویی",
            skinType: "بطری",
            effect: "",
            Durability: "",
            dis: "خانواده",
          },
        ],
      },
      {
        id: 9,
        category: "نوشابه",
        image: image9,
        title: "نوشابه پرتقالی میرندا ۱.۵ لیتری",
        Weight: "۱.۵ لیتری",
        priceReduction: "17,845",
        Discount: "20%",
        Price: "14,276",
        Brand: "میرندا ",
        Seller: "هایپر استار",
        ProductFeatures: [
          {
            id: 54,
            type: "پرتغالی",
            skinType: "بطری",
            effect: "",
            Durability: "",
            dis: "خانواده",
          },
        ],
      },
      {
        id: 10,
        category: "نوشابه",
        image: image10,
        title: "نوشابه کولا لاکیدو کاله ۱.۵ لیتری",
        Weight: "۱.۵ لیتری",
        priceReduction: "17,800",
        Discount: "25%",
        Price: "13,350",
        Brand: "کاله",
        Seller: "هایپر استار",
        ProductFeatures: [
          {
            id: 50,
             type: "کولا",
            skinType: "بطری",
            effect: "",
            Durability: "",
            dis: "خانواده",
          },
        ],
      },
      {
        id: 11,
        category: "نوشابه",
        image: image11,
        title: "نوشابه کولا پپسی ۳۰۰ میلی لیتری",
        Weight: "۳۰۰ میلی لیتری",
        priceReduction: "7,200",
        Discount: "20%",
        Price: "5,760",
        Brand: "پپسی",
        Seller: "هایپر استار",
        ProductFeatures: [
          {
            id: 55,
            type: "کولا",
            skinType: "بطری",
            effect: "",
            Durability: "",
            dis: "یکنفره",
          },
        ],
      },
      {
        id: 12,
        category: "ماءالشعیر",
        image: image12,
        title: "ماءالشعیر سیب جوجو ۱ لیتری",
        Weight: "۱ لیتری",
        priceReduction: "15,650",
        Discount: "12%",
        Price: "13,772",
        Brand: "جوجو ",
        Seller: "هایپر استار",
        ProductFeatures: [
          {
            id: 56,
             type: "سیب",
            skinType: "بطری",
            effect: "",
            Durability: "",
            dis: "خانواده",
          },
        ],
      },
      {
        id: 13,
        category: "ماءالشعیر",
        image: image13,
        title: " ماءالشعیر کلاسیک جوجو ۳۳۰ میلی لیتری",
        Weight: "۳۳۰ میلی لیتری",
        priceReduction: "",
        Discount: "",
        Price: "13,300",
        Brand: "جوجو",
        Seller: "هایپر استار",
        ProductFeatures: [
          {
            id: 57,
            type: "کلاسیک",
            skinType: "قوطی",
            effect: "",
            Durability: "",
            dis: "یکنفره",
          },
        ],
      },
      {
        id: 14,
        category: "ماءالشعیر",
        image: image14,
        title: "ماءالشعیر هلو هی دی ۳۳۰ میلی لیتری",
        Weight: "۳۳۰ میلی لیتری",
        priceReduction: "",
        Discount: "",
        Price: "13,655",
        Brand: "هی دی",
        Seller: "هایپر استار",
        ProductFeatures: [
          {
            id: 58,
            type: "هلو",
            skinType: "بطری",
            effect: "",
            Durability: "",
            dis: "یکنفره",
          },
        ],
      },
      {
        id: 15,
        category: "ماءالشعیر",
        image: image15,
        title: "ماءالشعیر آناناس دلستر ۱ لیتری",
        Weight: "۱ لیتری",
        priceReduction: "15,652",
        Discount: "20%",
        Price: "12,522",
        Brand: "دلستر",
        Seller: "هایپر استار",
        ProductFeatures: [
          {
            id: 59,
            type: "آناناس",
            skinType: "بطری",
            effect: "",
            Durability: "",
            dis: "خانواده",
          },
        ],
      },
      {
        id: 16,
        category: "ماءالشعیر",
        image: image16,
        title: "ماءالشعیر لیمویی مالت ایچ ۱ لیتر",
        Weight: "۱ لیتر",
        priceReduction: "19,000",
        Discount: "19%",
        Price: "15,390",
        Brand: "سن ایچ",
        Seller: "هایپر استار",
        ProductFeatures: [
          {
            id: 60,
            type: " ",
            skinType: "",
            effect: "",
            Durability: "",
            dis: "",
          },
        ],
      },
      {
        id: 17,
        category: "ماءالشعیر",
        image: image17,
        title: "ماءالشعیر مالت شمس ۱ لیتری",
        Weight: "۱ لیتری",
        priceReduction: "22,000",
        Discount: "25%",
        Price: "16,500",
        Brand: " شمس",
        Seller: "هایپر استار",
        ProductFeatures: [
          {
            id: 61,
            type: "کلاسیک ",
            skinType: "بطری",
            effect: "",
            Durability: "",
            dis: "خانواده",
          },
        ],
      },
      {
        id: 18,
        category: "ماءالشعیر",
        image: image18,
        title: "ماءالشعیر لیمویی جوجو ۱ لیتری",
        Weight: "۱ لیتری",
        priceReduction: "15,650",
        Discount: "12%",
        Price: "13,772",
        Brand: "جوجو",
        Seller: "هایپر استار",
        ProductFeatures: [
          {
            id: 62,
            type: "لیمو",
            skinType: "بطری",
            effect: "",
            Durability: "",
               dis: "خانواده",
          },
        ],
      },
      {
        id: 19,
        category: "ماءالشعیر",
        image: image19,
        title: "ماءالشعیر لیمویی دلستر ۳۳۰ میلی لیتری",
        Weight: "۳۳۰ میلی لیتری",
        priceReduction: "13,327",
        Discount: "20%",
        Price: "10,662",
        Brand: "دلستر",
        Seller: "هایپر استار",
        ProductFeatures: [
          {
            id: 63,
            type: "لیمو",
            skinType: "قوطی",
            effect: "",
            Durability: "",
            dis: "یکنفره",
          },
        ],
      },
      {
        id: 20,
        category: "ماءالشعیر",
        image: image20,
        title: "ماءالشعیر کلاسیک دلستر ۳۳۰ میلی لیتری",
        Weight: "۳۳۰ میلی لیتری",
        priceReduction: "13,327",
        Discount: "20%",
        Price: "10,662",
        Brand: "دلستر ",
        Seller: "هایپر استار",
        ProductFeatures: [
          {
            id: 64,
            type: "لیمو",
            skinType: "قوطی",
            effect: "",
            Durability: "",
            dis: "یکنفره",
          },
        ],
      },
      {
        id: 21,
        category: "ماءالشعیر",
        image: image21,
        title: "ماءالشعیر استوایی جوجو ۱ لیتری",
        Weight: " ۱ لیتری",
        priceReduction: "15,650",
        Discount: "12%",
        Price: "13,772",
        Brand: "جوجو ",
        Seller: "هایپر استار",
        ProductFeatures: [
          {
            id: 65,
            type: "استوایی",
            skinType: "بطری",
            effect: "",
            Durability: "",
            dis: "خانواده",
          },
        ],
      },
      {
        id: 22,
        category: "ماءالشعیر",
        image: image22,
        title: "ماءالشعیر هلو دلستر ۳۳۰ میلی لیتری",
        Weight: " ۳۳۰ میلی لیتری",
        priceReduction: "13و327",
        Discount: "20%",
        Price: "10و662",
        Brand: "دلستر",
        Seller: "هایپر استار",
        ProductFeatures: [
          {
            id: 66,
            type: "هلو",
            skinType: "قوطی",
            effect: "",
            Durability: "",
            dis: "یکنفره",
          },
        ],
      },
      {
        id: 23,
        category: "آبمیوه",
        image: image23,
        title: "نوشیدنی میکس مرکبات سن ایچ ۷۵۰ میلی لیتری",
        Weight: "۷۵۰ میلی لیتری",
        priceReduction: "",
        Discount: "",
        Price: "26,000",
        Brand: "سن ایچ ",
        Seller: "هایپر استار",
        ProductFeatures: [
          {
            id: 67,
            type: "چند میوه",
            skinType: "بزرگ",
            effect: "",
            Durability: "",
            dis: "پاکتی",
          },
        ],
      },
      {
        id: 24,
        category: "آبمیوه",
        image: image24,
        title: "نوشیدنی گازدار بلو هاوایی آیسی مانکی ۲۵۰ میلی لیتری",
        Weight: " ۲۵۰ میلی لیتری",
        priceReduction: "",
        Discount: "",
        Price: "18,000",
        Brand: " آیسی مانکی",
        Seller: "هایپر استار",
        ProductFeatures: [
          {
            id: 68,
            type: "کوچیک",
            skinType: "شیشه ای",
            effect: "",
            Durability: "",
            dis: "لیموناد",
          },
        ],
      },
      {
        id: 25,
        category: "آبمیوه",
        image: image25,
        title: "نکتار پرتقال پالپ دار سن ایچ ۱ لیتری",
        Weight: "  ۱ لیتری",
        priceReduction: "",
        Discount: "",
        Price: "45,000",
        Brand: "سن ایچ",
        Seller: "هایپر استار",
        ProductFeatures: [
          {
            id: 69,
            type: "پرتغال",
            skinType: "بزرگ",
            effect: "",
            Durability: "",
            dis: "پاکتی",
          },
        ],
      },
      {
        id: 26,
        category: "آبمیوه",
        image: image26,
        title: "نوشیدنی گازدار سیب و کیوی آیسی مانکی ۲۵۰ میلی لیتری",
        Weight: "۲۵۰ میلی لیتری",
        priceReduction: "",
        Discount: "",
        Price: "18,000",
        Brand: "آیسی مانکی",
        Seller: "هایپر استار",
        ProductFeatures: [
          {
            id: 70,
            type: "چند میوه",
            skinType: "کوچک",
            effect: "",
            Durability: "",
            dis: "شیشه ای",
          },
        ],
      },
      {
        id: 27,
        category: "آبمیوه",
        image: image27,
        title: "نکتار هلو سن ایچ ۱ لیتری",
        Weight: " ۱ لیتری",
        priceReduction: "",
        Discount: "",
        Price: "45,000",
        Brand: "سن ایچ",
        Seller: "هایپر استار",
        ProductFeatures: [
          {
            id: 71,
            type: "هلو",
            skinType: "بزرگ",
            effect: "",
            Durability: "",
            dis: "پاکتی",
          },
        ],
      },
      {
        id: 28,
        category: "آبمیوه",
        image: image28,
        title: "نوشیدنی گازدار پرتقالی سن ایچ ۱ لیتری",
        Weight: "۱ لیتری",
        priceReduction: "20,000",
        Discount: "19%",
        Price: "16,200",
        Brand: "سن ایچ",
        Seller: "هایپر استار",
        ProductFeatures: [
          {
            id: 72,
            type: "پرتغال",
            skinType: "بزرگ",
            effect: "",
            Durability: "",
            dis: "بطری",
          },
        ],
      },
      {
        id: 29,
        category: "آبمیوه",
        image: image29,
        title: "نکتار آناناس کودک سن ایچ ۲۰۰ میلی لیتری",
        Weight: "۲۰۰ میلی لیتری",
        priceReduction: "",
        Discount: "",
        Price: "10,000",
        Brand: "سن ایچ ",
        Seller: "هایپر استار",
        ProductFeatures: [
          {
            id: 73,
            type: "",
            skinType: "",
            effect: "",
            Durability: "",
            dis: "",
          },
        ],
      },
      {
        id: 30,
        category: "آبمیوه",
        image: image30,
        title: "نکتار آلبالو سن ایچ ۱ لیتری",
        Weight: "۱ لیتری",
        priceReduction: "",
        Discount: "",
        Price: "45,000",
        Brand: "سن ایچ ",
        Seller: "هایپر استار",
        ProductFeatures: [
          {
            id: 74,
            type: "آلبالو",
            skinType: "بزرگ",
            effect: "",
            Durability: "",
            dis: "پاکتی",
          },
        ],
      },
      {
        id: 31,
        category: "آبمیوه",
        image: image31,
        title: "نکتار بلوبری و انار و لیمو سان استار ۷۵۰ میلی لیتری",
        Weight: "۷۵۰ میلی لیتری",
        priceReduction: "",
        Discount: "",
        Price: "48,000",
        Brand: "سان استار",
        Seller: "هایپر استار",
        ProductFeatures: [
          {
            id: 75,
            type: "",
            skinType: "",
            effect: "",
            Durability: "",
            dis: "",
          },
        ],
      },
      {
        id: 32,
        category: "آبمیوه",
        image: image32,
        title: "نوشیدنی لیموناد سن ایچ ۲۰۰ میلی لیتری",
        Weight: "۲۰۰ میلی لیتری",
        priceReduction: "",
        Discount: "",
        Price: "10,000",
        Brand: "سن ایچ",
        Seller: "هایپر استار",
        ProductFeatures: [
          {
            id: 76,
            type: "کوچک ",
            skinType: "لیموناد",
            effect: "",
            Durability: "",
            dis: "پاکتی",
          },
        ],
      },
      {
        id: 33,
        category: "آبمیوه",
        image: image33,
        title: "نکتار پرتقال سان تاپ ۲۰۰ میلی لیتری",
        Weight: "۲۰۰ میلی لیتری",
        priceReduction: "",
        Discount: "",
        Price: "7,300",
        Brand: "سان تاپ",
        Seller: "هایپر استار",
        ProductFeatures: [
          {
            id: 77,
            type: "پرتغال",
            skinType: "کوچک",
            effect: "",
            Durability: "",
            dis: "پاکتی",
          },
        ],
      },
      // {
      //   id: 34,
      //   category: "چای و دمنوش",
      //   image: image34,
      //   title: "چای و دمنوش بدون گاز پونه هراز ۱.۵ لیتری",
      //   Weight: "۱.۵ لیتری",
      //   priceReduction: "26,900",
      //   Discount: "18%",
      //   Price: "22,058",
      //   Brand: "هراز",
      //   Seller: "هایپر استار",
      //   ProductFeatures: [
      //     {
      //       id: 78,
      //       type: "بدون گاز",
      //       skinType: "",
      //       effect: "",
      //       Durability: "",
      //       dis: "با سبزی معطر",
      //     },
      //   ],
      // },
      // {
      //   id: 35,
      //   category: "چای و دمنوش",
      //   image: image35,
      //   title: "چای و دمنوش گازدار هراز ۱.۵ لیتری",
      //   Weight: "۱.۵ لیتری",
      //   priceReduction: "27,900",
      //   Discount: "20%",
      //   Price: "22,320",
      //   Brand: " هراز ",
      //   Seller: "هایپر استار",
      //   ProductFeatures: [
      //     {
      //       id: 79,
      //       type: "گاز دار",
      //       skinType: "",
      //       effect: "",
      //       Durability: "",
      //       dis: "",
      //     },
      //   ],
      // },
      // {
      //   id: 36,
      //   category: "چای و دمنوش",
      //   image: image36,
      //   title: "چای و دمنوش بدون گاز ترش گلپر هراز ۱.۵ لیتری",
      //   Weight: "۱.۵ لیتری",
      //   priceReduction: "26,900",
      //   Discount: "20%",
      //   Price: "21,520",
      //   Brand: "هراز",
      //   Seller: "هایپر استار",
      //   ProductFeatures: [
      //     {
      //       id: 80,
      //       type: "بدون گاز",
      //       skinType: "",
      //       effect: "",
      //       Durability: "",
      //       dis: "با سبزی معطر",
      //     },
      //   ],
      // },
      // {
      //   id: 37,
      //   category: "چای و دمنوش",
      //   image: image37,
      //   title: "چای و دمنوش بدون گاز گرمادیده کاله ۱.۵ لیتری",
      //   Weight: "۱.۵ لیتری",
      //   priceReduction: "27,000",
      //   Discount: "25%",
      //   Price: "20,250",
      //   Brand: "کاله",
      //   Seller: "هایپر استار",
      //   ProductFeatures: [
      //     {
      //       id: 81,
      //       type: "بدون گاز",
      //       skinType: "",
      //       effect: "",
      //       Durability: "",
      //       dis: "",
      //     },
      //   ],
      // },
      // {
      //   id: 38,
      //   category: "چای و دمنوش",
      //   image: image38,
      //   title: "چای و دمنوش بدون گاز سبزیجات دلال گرمادیده هراز ۱.۵ لیتری",
      //   Weight: "۱.۵ لیتری",
      //   priceReduction: "29,800",
      //   Discount: "15%",
      //   Price: "25,330",
      //   Brand: "هراز ",
      //   Seller: "هایپر استار",
      //   ProductFeatures: [
      //     {
      //       id: 82,
      //       type: "بدون گاز",
      //       skinType: "",
      //       effect: "",
      //       Durability: "",
      //       dis: "با سبزی معطر",
      //     },
      //   ],
      // },
      // {
      //   id: 39,
      //   category: "چای و دمنوش",
      //   image: image39,
      //   title: "چای و دمنوش بدون گاز هشت گیاه عالیس ۱.۵ لیتری",
      //   Weight: "۱.۵ لیتری",
      //   priceReduction: "27,000",
      //   Discount: "9%",
      //   Price: "24,570",
      //   Brand: " عالیس ",
      //   Seller: "هایپر استار",
      //   ProductFeatures: [
      //     {
      //       id: 83,
      //       type: "بدون گاز",
      //       skinType: "",
      //       effect: "",
      //       Durability: "",
      //       dis: "با سبزی معطر",
      //     },
      //   ],
      // },
      // {
      //   id: 40,
      //   category: "چای و دمنوش",
      //   image: image40,
      //   title: "چای و دمنوش بدون گاز نعنایی گرمادیده صباح ۱.۵ لیتری",
      //   Weight: "۱.۵ لیتری",
      //   priceReduction: "26,000",
      //   Discount: "23%",
      //   Price: "20,020",
      //   Brand: "صباح",
      //   Seller: "هایپر استار",
      //   ProductFeatures: [
      //     {
      //       id: 84,
      //       type: "بدون گاز",
      //       skinType: "",
      //       effect: "",
      //       Durability: "",
      //       dis: "",
      //     },
      //   ],
      // },
      // {
      //   id: 41,
      //   category: "چای و دمنوش",
      //   image: image41,
      //   title: "چای و دمنوش بدون گاز نعنایی هراز ۹۰۰ میلی لیتری",
      //   Weight: "۹۰۰ میلی لیتری",
      //   priceReduction: "",
      //   Discount: "",
      //   Price: "10,900",
      //   Brand: "هراز",
      //   Seller: "هایپر استار",
      //   ProductFeatures: [
      //     {
      //       id: 85,
      //       type: "بدون گاز",
      //       skinType: "",
      //       effect: "",
      //       Durability: "",
      //       dis: "با سبزی معطر",
      //     },
      //   ],
      // },
      // {
      //   id: 42,
      //   category: "چای و دمنوش",
      //   image: image42,
      //   title: "چای و دمنوش بدون گاز نعنا و پونه کاله ۹۰۰ گرمی",
      //   Weight: "۹۰۰ گرمی",
      //   priceReduction: "",
      //   Discount: "",
      //   Price: "12,000",
      //   Brand: "کاله",
      //   Seller: "هایپر استار",
      //   ProductFeatures: [
      //     {
      //       id: 86,
      //       type: "بدون گاز",
      //       skinType: "",
      //       effect: "",
      //       Durability: "",
      //       dis: "با سبزی معطر",
      //     },
      //   ],
      // },
      // {
      //   id: 43,
      //   category: "چای و دمنوش",
      //   image: image43,
      //   title: "چای و دمنوش بدون گاز گلپر هراز ۹۰۰ میلی لیتری",
      //   Weight: "۹۰۰ میلی لیتری",
      //   priceReduction: "",
      //   Discount: "",
      //   Price: "10,900",
      //   Brand: "کاله",
      //   Seller: "هایپر استار",
      //   ProductFeatures: [
      //     {
      //       id: 87,
      //       type: "بدون گاز",
      //       skinType: "",
      //       effect: "",
      //       Durability: "",
      //       dis: "با سبزی معطر",
      //     },
      //   ],
      // },
      // {
      //   id: 44,
      //   category: "چای و دمنوش",
      //   image: image44,
      //   title: "چای و دمنوش بدون گاز نعنایی عالیس ۲۷۵ میلی لیتری",
      //   Weight: "۲۷۵ میلی لیتری",
      //   priceReduction: "",
      //   Discount: "",
      //   Price: "7,500",
      //   Brand: "عالیس",
      //   Seller: "هایپر استار",
      //   ProductFeatures: [
      //     {
      //       id: 88,
      //       type: "بدون گاز",
      //       skinType: "",
      //       effect: "",
      //       Durability: "",
      //       dis: "با سبزی معطر",
      //     },
      //   ],
      // },


    ],
  },
];
