import image1 from "../../assets/Images/ImageDataBase/Appliances/image1.jpg";
import image2 from "../../assets/Images/ImageDataBase/Appliances/image2.jpg";
import image3 from "../../assets/Images/ImageDataBase/Appliances/image3.jpg";
import image4 from "../../assets/Images/ImageDataBase/Appliances/image4.jpg";
import image5 from "../../assets/Images/ImageDataBase/Appliances/image5.jpg";
import image6 from "../../assets/Images/ImageDataBase/Appliances/image6.jpg";
import image7 from "../../assets/Images/ImageDataBase/Appliances/image7.jpg";
import image8 from "../../assets/Images/ImageDataBase/Appliances/image8.jpg";
import image9 from "../../assets/Images/ImageDataBase/Appliances/image9.jpg";
import image10 from "../../assets/Images/ImageDataBase/Appliances/image10.jpg";
import image11 from "../../assets/Images/ImageDataBase/Appliances/image11.jpg";
import image12 from "../../assets/Images/ImageDataBase/Appliances/image12.jpg";
import image13 from "../../assets/Images/ImageDataBase/Appliances/image13.jpg";
import image14 from "../../assets/Images/ImageDataBase/Appliances/image14.jpg";
import image15 from "../../assets/Images/ImageDataBase/Appliances/image15.jpg";
import image16 from "../../assets/Images/ImageDataBase/Appliances/image16.jpg";
import image17 from "../../assets/Images/ImageDataBase/Appliances/image17.jpg";
import image18 from "../../assets/Images/ImageDataBase/Appliances/image17.jpg";
import image19 from "../../assets/Images/ImageDataBase/Appliances/image19.jpg";
import image20 from "../../assets/Images/ImageDataBase/Appliances/image20.jpg";
import image21 from "../../assets/Images/ImageDataBase/Appliances/image21.jpg";
import image22 from "../../assets/Images/ImageDataBase/Appliances/image22.jpg";
import image23 from "../../assets/Images/ImageDataBase/Appliances/image23.jpg";
import image24 from "../../assets/Images/ImageDataBase/Appliances/image24.jpg";
import image25 from "../../assets/Images/ImageDataBase/Appliances/image25.jpg";
import image26 from "../../assets/Images/ImageDataBase/Appliances/image26.jpg";
import image27 from "../../assets/Images/ImageDataBase/Appliances/image27.jpg";
import image28 from "../../assets/Images/ImageDataBase/Appliances/image28.jpg";
import image29 from "../../assets/Images/ImageDataBase/Appliances/image29.jpg";
import image30 from "../../assets/Images/ImageDataBase/Appliances/image30.jpg";
import image31 from "../../assets/Images/ImageDataBase/Appliances/image31.jpg";
import image32 from "../../assets/Images/ImageDataBase/Appliances/image32.jpg";
import image33 from "../../assets/Images/ImageDataBase/Appliances/image33.jpg";
import image34 from "../../assets/Images/ImageDataBase/Appliances/image34.jpg";
import image35 from "../../assets/Images/ImageDataBase/Appliances/image35.jpg";
import image36 from "../../assets/Images/ImageDataBase/Appliances/image36.jpg";
import image37 from "../../assets/Images/ImageDataBase/Appliances/image37.jpg";

export const DataBaseAppliances = [
  {
    id: 1,
    name: "لوازم برقی و دیجیتال",
    categories: [
      "باتری، محافظ و رابط",
      "نور و روشنایی",
      "لوازم برقی خانه",
      "لوازم برقی آشپزخانه",
    ],
    appliances: [
      {
        id: 1,
        category: "باتری، محافظ و رابط",
        image: image1,
        title: "باتری قلمی AA بیلستری کملیون",
        Weight: " 2 عددی",
        priceReduction: "12,900",
        Discount: "%15",
        price: 10965,
        Brand: "کملیون",
      },
      {
        id: 2,
        category: "باتری، محافظ و رابط",
        image: image2,
        title: "باتری قلمی Digi Alkaline کملیون",
        Weight: " 2 عددی",
        priceReduction: "",
        Discount: "",
        price: 27900,
        Brand: "کملیون",
      },
      {
        id: 3,
        category: "باتری، محافظ و رابط",
        image: image3,
        title: "باتری نیم قلمی AAA بیلستری کملیون",
        Weight: " 2 عددی",
        priceReduction: "",
        Discount: "",
        price: 12900,
        Brand: "کملیون",
      },
      {
        id: 4,
        category: "باتری، محافظ و رابط",
        image: image4,
        title: "باتری نیم قلمی دیجی آلکالاین کملیون",
        Weight: " 2 عددی",
        priceReduction: "",
        Discount: "",
        price: "27,900",
        Brand: "کملیون",
      },
      {
        id: 5,
        category: "باتری، محافظ و رابط",
        image: image5,
        title: "باتری قلمی Digi Alkaline کملیون",
        Weight: " 12 عددی",
        priceReduction: "",
        Discount: "",
        price: 12900,
        Brand: "کملیون",
      },
      {
        id: 6,
        category: "باتری، محافظ و رابط",
        image: image6,
        title: "باتری قلمی AA شرینک کملیون",
        Weight: " 4 عددی",
        priceReduction: "",
        Discount: "",
        price: 20900,
        Brand: "کملیون",
      },
      {
        id: 7,
        category: "باتری، محافظ و رابط",
        image: image7,
        title: "باتری نیم قلمی AAA شرینک کملیون",
        Weight: " 4 عددی",
        priceReduction: "",
        Discount: "",
        price:20900,
        Brand: "کملیون",
      },
      {
        id: 8,
        category: "باتری، محافظ و رابط",
        image: image8,
        title: "باتری نیم قلم و قلمی کملیون",
        Weight: " 8 عددی",
        priceReduction: "",
        Discount: "",
        price: 42900,
        Brand: "کملیون",
      },
      {
        id: 9,
        category: "باتری، محافظ و رابط",
        image: image9,
        title: "باتری نیم قلمی Digi Alkaline کملیون",
        Weight: " 4 عددی",
        priceReduction: "",
        Discount: "",
        price: 48900,
        Brand: "کملیون",
      },
      {
        id: 10,
        category: "باتری، محافظ و رابط",
        image: image10,
        title: "باتری قلمی آلکالاین AA کملیون ",
        Weight: " 4 عددی",
        priceReduction: "",
        Discount: "",
        price: 48900,
        Brand: "کملیون",
      },
      {
        id: 11,
        category: "باتری، محافظ و رابط",
        image: image11,
        title: "باتری قلمی دیجی آلکالاین کملیون",
        Weight: " 4 عددی",
        priceReduction: "",
        Discount: "",
        price: 46900,
        Brand: "کملیون",
      },
      {
        id: 12,
        category: "نور و روشنایی",
        image: image12,
        title: "لامپ حبابی مهتابی سیدکو ۱۲ وات",
        Weight: "",
        priceReduction: "43,900",
        Discount: "11%",
        price: 39071,
        Brand: "سیدکو",
      },
      {
        id: 13,
        category: "نور و روشنایی",
        image: image13,
        title: "لامپ حبابی آفتابی ۹ وات سیکدو",
        Weight: "",
        priceReduction: "36,900",
        Discount: "11%",
        price: 32841,
        Brand: "سیدکو",
      },
      {
        id: 14,
        category: "نور و روشنایی",
        image: image14,
        title: "لامپ اشکی آفتابی ۶ وات کارامکس",
        Weight: "",
        priceReduction: "38,500",
        Discount: "12%",
        price: 33880,
        Brand: "سیدکو",
      },
      {
        id: 15,
        category: "نور و روشنایی",
        image: image15,
        title: "لامپ حبابی مهتابی ۱۵ وات سیدکو",
        Weight: "",
        priceReduction: "59,900",
        Discount: "11%",
        price: 53331,
        Brand: "سیدکو",
      },
      {
        id: 16,
        category: "نور و روشنایی",
        image: image16,
        title: "لامپ شمعی ۷ وات آفتابی سیدکو",
        Weight: "",
        priceReduction: "",
        Discount: "",
        price: 38900,
        Brand: "سیدکو",
      },
      {
        id: 17,
        category: "نور و روشنایی",
        image: image17,
        title: "لامپ حبابی آفتابی سیدکو ۱۵ وات",
        Weight: "",
        priceReduction: "",
        Discount: "",
        price: 59900,
        Brand: "سیدکو",
      },
      {
        id: 18,
        category: "نور و روشنایی",
        image: image18,
        title: "لامپ حبابی ۱۸ وات مهتابی سیدکو",
        Weight: "",
        priceReduction: "",
        Discount: "",
        price: 81900,
        Brand: "سیدکو",
      },
      {
        id: 19,
        category: "نور و روشنایی",
        image: image19,
        title: "لامپ LED مهتابی کارامکس ۱۲ وات",
        Weight: "",
        priceReduction: "",
        Discount: "",
        price: 79600,
        Brand: "سیدکو",
      },
      {
        id: 20,
        category: "نور و روشنایی",
        image: image20,
        title: "لامپ LED مهتابی کارامکس ۱۲ وات",
        Weight: "",
        priceReduction: "44,500",
        Discount: "3%",
        price: 43165,
        Brand: "سیدکو",
      },
      {
        id: 21,
        category: "نور و روشنایی",
        image: image21,
        title: "لامپ ال ای دی مهتابی ۱۲ وات کملیون",
        Weight: "",
        priceReduction: "",
        Discount: "",
        price:44000,
        Brand: "سیدکو",
      },
      {
        id: 22,
        category: "نور و روشنایی",
        image: image22,
        title: "لامپ LED هالوژن آفتابی کملیون ۷ وات",
        Weight: "",
        priceReduction: "",
        Discount: "",
        price: 40000,
        Brand: "سیدکو",
      },
      {
        id: 23,
        category: "لوازم برقی خانه",
        image: image23,
        title: "کولر گازی سرد و گرم MPF-۲۴CH سفید سری Forest پاکشوما ۲۴۰۰۰",
        Brand: "پاکشوما",
        Weight: "",
        priceReduction: "24,750,000",
        Discount: "7%",
        price: 23017500,
        ProductFeatures: [
          {
            id: 43,
            type: "اسپلیت",
            color: "سفید",
            Capacity: "۱۸ هزار",
            dis: "مناسب مناطق معتدل و گرم  دارای کمپرسور روتاری GMCC",
            sizePanel: "۹۵.۷x۲۱.۳x۳۰.۲ سانتی متر",
            amountOfWind: " تا ۱۰ متر",
            CondenserSize: "۷۷x۳۰x۵۵.۵ سانتی متر",
            InnerPanelWeight: "۱۱.۱ کیلوگرم",
            ExternalNnitWeight: "۴۰ کیلوگرم",
            TheVolumeOfTheInternalPanel: "۳۶.۵ دسی بل",
            TheVolumeOfTheExternalUnit: "۵۷ دسی بل",
            Description: "مناسب مناطق معتدل و گرم ",
          },
        ],
      },
      {
        id: 24,
        category: "لوازم برقی خانه",
        image: image24,
        title: "کولر گازی سرد و گرم ACO۱۸ سفید کنوود ۱۸۰۰۰",
        Brand: "کنوود",
        Weight: "",
        priceReduction: "",
        Discount: "",
        price: 22015000,
        ProductFeatures: [
          {
            id: 44,
            type: "اسپلیت",
            color: "سفید",
            Capacity: "۱۸ هزار",
            dis: "مناسب مناطق معتدل و گرم",
            sizePanel: "۹۰x۲۲.۵x۳۱ سانتی متری",
            amountOfWind: "تا ۱۵ متر",
            CondenserSize: "۸۰x۳۱.۵x۵۴.۵ سانتی متر",
            InnerPanelWeight: "۱۱.۵ کیلوگرم",
            ExternalNnitWeight: " ۳۸ کیلوگرم",
            TheVolumeOfTheInternalPanel: "۴۸ دسی بل",
            TheVolumeOfTheExternalUnit: "۵۶ دسی بل",
            Description: "دارای کمپرسور نسل جدید High Efficiency",
          },
        ],
      },
      {
        id: 25,
        category: "لوازم برقی خانه",
        image: image25,
        title: "کولر گازی سرد و گرم اینورتر ACI۱۸ سفید کنوود ۱۸۰۰۰",
        Brand: "کنوود",
        Weight: "",
        priceReduction: "",
        Discount: "",
        price: 25385000,
        ProductFeatures: [
          {
            id: 45,
            type: "اسپلیت",
            color: "سفید",
            Capacity: "۱۸ هزار",
            dis: "مناسب مناطق معتدل و گرم",
            sizePanel: "۹۵.۲x۲۲.۷x۳۱ سانتی متری",
            amountOfWind: "تا ۱۵ متر",
            CondenserSize: "۸۰x۳۱.۵x۵۴.۵ سانتی متر",
            InnerPanelWeight: "۱۲.۵ کیلوگرم",
            ExternalNnitWeight: "۳۴ کیلوگرم",
            TheVolumeOfTheInternalPanel: "۴۷ دسی بل",
            TheVolumeOfTheExternalUnit: "۵۵ دسی بل",
            Description: "دارای کمپرسور نسل جدید High Efficiency",
          },
        ],
      },
      {
        id: 26,
        category: "لوازم برقی خانه",
        image: image26,
        title: "کولر گازی سرد و گرم اینورتر ACI۲۴ سفید کنوود ۲۴۰۰۰",
        Brand: "کنوود",
        Weight: "",
        priceReduction: "",
        Discount: "",
        price: 31500000,
        ProductFeatures: [
          {
            id: 46,
            type: "اسپلیت",
            color: "سفید",
            Capacity: "۲۴ هزار",
            dis: "مناسب مناطق معتدل و گرم",
            sizePanel: "۱۰۸.۲x۲۳.۳x۳۳ سانتی متری",
            amountOfWind: " تا ۱۵ متر",
            CondenserSize: "۸۲.۵x۳۱x۶۵.۵ سانتی متر",
            InnerPanelWeight: "۱۴ کیلوگرم",
            ExternalNnitWeight: "۴۰ کیلوگرم",
            TheVolumeOfTheInternalPanel: "۵۰ دسی بل",
            TheVolumeOfTheExternalUnit: "۵۷ دسی بل",
            Description: "دارای کمپرسور نسل جدید High Efficiency",
          },
        ],
      },
      {
        id: 27,
        category: "لوازم برقی خانه",
        image: image26,
        title: "کولر گازی سرد و گرم MPF-۰۹CH سفید سری Forest پاکشوما ۹۰۰۰",
        Brand: "پاکشوما",
        Weight: "",
        priceReduction: "",
        Discount: "",
        price: 13750000,
        ProductFeatures: [
          {
            id: 47,
            type: "اسپلیت",
            color: "سفید",
            Capacity: "۹ هزار",
            dis: "مناسب مناطق معتدل و گرم",
            sizePanel: "۷۱.۵x۱۹.۵x۲۸.۵ سانتی متر",
            amountOfWind: " تا ۱۰ متر",
            CondenserSize: "۷۰x۲۷.۵x۵۵ سانتی متر",
            InnerPanelWeight: "۷.۷ کیلوگرم",
            ExternalNnitWeight: " ۲۶.۷ کیلوگرم",
            TheVolumeOfTheInternalPanel: "۳۲ دسی بل",
            TheVolumeOfTheExternalUnit: "۵۳ دسی بل",
            Description:
              "مجهز به اواپراتور و کندانسور با پره های طلایی، مقاوم در برابر خوردگی (Golden Fin)",
          },
        ],
      },
      {
        id: 28,
        category: "لوازم برقی خانه",
        image: image26,
        title: "کولر گازی سرد و گرم MPF-۱۲CH سفید سری Forest پاکشوما ۱۲۰۰۰",
        Brand: "پاکشوما",
        Weight: "",
        priceReduction: "",
        Discount: "",
        price: 15230000,
        ProductFeatures: [
          {
            id: 48,
            type: "اسپلیت",
            color: "سفید",
            Capacity: " ۱۲ هزار",
            dis: "مناسب مناطق معتدل و گرم",
            sizePanel: "۸۰.۵x۱۹.۴x۲۸.۵ سانتی متر",
            amountOfWind: " تا ۱۰ متر",
            CondenserSize: "۹۰x۳۴.۵x۵۸.۵ سانتی متر",
            InnerPanelWeight: "۷.۷ کیلوگرم",
            ExternalNnitWeight: "۳۰ کیلوگرم",
            TheVolumeOfTheInternalPanel: "۳۶ دسی بل",
            TheVolumeOfTheExternalUnit: "۵۶ دسی بل",
            Description:
              "مجهز به اواپراتور و کندانسور با پره های طلایی، مقاوم در برابر خوردگی (Golden Fin)",
          },
        ],
      },
      {
        id: 29,
        category: "لوازم برقی خانه",
        image: image26,
        title: "کولر گازی سرد و گرم MPF-۱۲CH سفید سری Forest پاکشوما ۱۲۰۰۰",
        Brand: "پاکشوما",
        Weight: "",
        priceReduction: "",
        Discount: "",
        price: 12550000,
        ProductFeatures: [
          {
            id: 49,
            type: "اسپلیت",
            color: "سفید",
            Capacity: "۱۲ هزار",
            dis: "مناسب مناطق معتدل و گرم",
            sizePanel: "۸۰.۵x۱۹.۴x۲۸.۵ سانتی متر",
            amountOfWind: "تا ۱۰ متر",
            CondenserSize: "۹۰x۳۴.۵x۵۸.۵ سانتی متر",
            InnerPanelWeight: " ۷.۷ کیلوگرم",
            ExternalNnitWeight: "۳۰ کیلوگرم",
            TheVolumeOfTheInternalPanel: "۳۶ دسی بل",
            TheVolumeOfTheExternalUnit: " ۵۶ دسی بل",
            Description:
              "مجهز به اواپراتور و کندانسور با پره های طلایی، مقاوم در برابر خوردگی (Golden Fin)",
          },
        ],
      },
      {
        id: 30,
        category: "لوازم برقی خانه",
        image: image26,
        title: "کولر گازی سرد و گرم MPF-۱۸CH سفید سری Forest پاکشوما ۱۸۰۰۰",
        Brand: "پاکشوما",
        Weight: "",
        priceReduction: "",
        Discount: "",
        price: 206550000,
        ProductFeatures: [
          {
            id: 50,
            type: "اسپلیت",
            color: "سفید",
            Capacity: "۱۸ هزار",
            dis: "مناسب مناطق معتدل و گرم",
            sizePanel: "۹۵.۷x۲۱.۳x۳۰.۲ سانتی متر",
            amountOfWind: " تا ۱۰ متر",
            CondenserSize: " ۷۷x۳۰x۵۵.۵ سانتی متر",
            InnerPanelWeight: "۱۱.۱ کیلوگرم",
            ExternalNnitWeight: "۴۰ کیلوگرم",
            TheVolumeOfTheInternalPanel: "۳۶.۵ دسی بل",
            TheVolumeOfTheExternalUnit: "۵۷ دسی بل",
            Description:
              "مجهز به اواپراتور و کندانسور با پره های طلایی، مقاوم در برابر خوردگی (Golden Fin)",
          },
        ],
      },
      {
        id: 31,
        category: "لوازم برقی خانه",
        image: image26,
        title: "کولر گازی سرد و گرم ACO۲۴ سفید کنوود ۲۴۰۰۰",
        Brand: "کنوود",
        Weight: "",
        priceReduction: "",
        Discount: "",
        price: 25900000,
        ProductFeatures: [
          {
            id: 51,
            type: "اسپلیت",
            color: "سفید",
            Capacity: "۲۴ هزار",
            dis: "مناسب مناطق معتدل و گرم",
            sizePanel: "۱۰۸.۲x۲۳.۳x۳۳ سانتی متری",
            amountOfWind: "تا ۱۵ متر",
            CondenserSize: "۸۲.۵x۳۱x۶۵.۵ سانتی متر",
            InnerPanelWeight: "۱۴ کیلوگرم",
            ExternalNnitWeight: "۴۸ کیلوگرم",
            TheVolumeOfTheInternalPanel: "۴۸ دسی بل",
            TheVolumeOfTheExternalUnit: "۵۷ دسی بل",
            Description: "دارای کمپرسور نسل جدید High Efficiency",
          },
        ],
      },
      {
        id: 32,
        category: "لوازم برقی آشپزخانه",
        image: image27,
        title: "ماشین لباسشویی PWN-۹۶۵۴AJ سفید پاکشوما ۹.۶ کیلوگرمی",
        Brand: "پاکشوما",
        Weight: "",
        priceReduction: "",
        Discount: "",
        price: 3600000,
        ProductFeatures: [
          {
            id: 52,
            type: "نیمه اتوماتیک",
            color: "سفید",
            Capacity: "۹.۶ کیلوگرم",
            dis: "قابلیت تنظیم زمان خشک کن و شستشو",
            sizePanel: "۸۰x۴۷x۹۶ سانتی متر",
            amountOfWind: "",
            CondenserSize: "",
            InnerPanelWeight: "",
            ExternalNnitWeight: "",
            TheVolumeOfTheInternalPanel: "",
            TheVolumeOfTheExternalUnit: "",
            Description: " دارای ۱۸ ماه ضمانت + ۱۴۴ ماه خدمات پس از فروش پاک سرویس ۷ روز ضمانت بازگشت در صورت باز نشدن پلمپ کالا",
          },
        ],
      },
      {
        id: 33,
        category: "لوازم برقی آشپزخانه",
        image: image28,
        title: "ماشین لباسشویی TFB-۸۵۴۰۲WT سفید سری L پاکشوما ۸ کیلوگرمی",
        Brand: "پاکشوما",
        Weight: "",
        priceReduction: "",
        Discount: "",
        price: 13900000,
        ProductFeatures: [
          {
            id: 53,
            type: " اتوماتیک",
            color: "سفید",
            Capacity: "8 کیلوگرم",
            dis: "قابلیت تنظیم زمان خشک کن و شستشو",
            sizePanel: "",
            amountOfWind: "",
            CondenserSize: "",
            InnerPanelWeight: "",
            ExternalNnitWeight: "",
            TheVolumeOfTheInternalPanel: "",
            TheVolumeOfTheExternalUnit: "۵۹ دسی بل",
            Description: "دارای ۱۶ برنامه شستشوی اصلی و ۴ برنامه کمکی",
          },
        ],
      },
      {
        id: 34,
        category: "لوازم برقی آشپزخانه",
        image: image29,
        title: "ماشین ظرفشویی MDF-۱۴۳۰۲W سفید سری Josephine پاکشوما ۱۴ نفره",
        Brand: "پاکشوما",
        Weight: "",
        priceReduction: "",
        Discount: "",
        price: 17400000,
        ProductFeatures: [
          {
            id: 54,
            type: "نیمه اتوماتیک",
            color: "سفید",
            Capacity: "۹.۶ کیلوگرم",
            dis: "قابلیت تنظیم زمان خشک کن و شستشو",
            sizePanel: "",
            amountOfWind: "",
            CondenserSize: "",
            InnerPanelWeight: "",
            ExternalNnitWeight: "",
            TheVolumeOfTheInternalPanel: "",
            TheVolumeOfTheExternalUnit: "",
            Description: "",
          },
        ],
      },
      {
        id: 35,
        category: "لوازم برقی آشپزخانه",
        image: image30,
        title: "ماشین ظرفشویی MDF-۱۴۳۰۲S سیلور سری Josephine پاکشوما ۱۴ نفره",
        Brand: "پاکشوما",
        Weight: "",
        priceReduction: "",
        Discount: "",
        price: 18000000,
        ProductFeatures: [
          {
            id: 55,
            type: "ایستاده",
            color: "سفید",
            Capacity: " ۱۵ نفره",
            dis: "قابلیت تنظیم زمان خشک کن و شستشو",
            sizePanel: "۸۵x۶۰x۶۰ سانتی متر",
            amountOfWind: "",
            CondenserSize: "",
            InnerPanelWeight: "",
            ExternalNnitWeight: "",
            TheVolumeOfTheInternalPanel: "۴۲ دسی بل",
            TheVolumeOfTheExternalUnit: "",
            Description: "",
          },
        ],
      },
      {
        id: 36,
        category: "لوازم برقی آشپزخانه",
        image: image31,
        title: "ماشین ظرفشویی MDF-۱۵۳۰۵W سفید پاکشوما ۱۵ نفره",
        Brand: "پاکشوما",
        Weight: "",
        priceReduction: "",
        Discount: "",
        price: 17530000,
        ProductFeatures: [
          {
            id: 56,
            type: "ایستاده",
            color: "سفید",
            Capacity: " ۱۵ نفره",
            dis: "قابلیت تنظیم زمان خشک کن و شستشو",
            sizePanel: "۸۵x۶۰x۶۰ سانتی متر",
            amountOfWind: "",
            CondenserSize: "",
            InnerPanelWeight: "",
            ExternalNnitWeight: "",
            TheVolumeOfTheInternalPanel: "",
            TheVolumeOfTheExternalUnit: "",
            Description: "",
          },
        ],
      },
      {
        id: 37,
        category: "لوازم برقی آشپزخانه",
        image: image32,
        title: "ماشین ظرفشویی MDF-۱۵۳۰۵S سیلور پاکشوما ۱۵ نفره",
        Brand: "پاکشوما",
        Weight: "",
        priceReduction: "",
        Discount: "",
        price: 17800000,
        ProductFeatures: [
          {
            id: 57,
            type: "نیمه اتوماتیک",
            color: "سفید",
            Capacity: "۹.۶ کیلوگرم",
            dis: "قابلیت تنظیم زمان خشک کن و شستشو",
            sizePanel: "",
            amountOfWind: "",
            CondenserSize: "",
            InnerPanelWeight: "",
            ExternalNnitWeight: "",
            TheVolumeOfTheInternalPanel: "",
            TheVolumeOfTheExternalUnit: "",
            Description: "",
          },
        ],
      },
      {
        id: 38,
        category: "لوازم برقی آشپزخانه",
        image: image33,
        title: "ماشین ظرفشویی MDF-۱۵۳۰۲W سفید سری Josephine پاکشوما ۱۵ نفره",
        Brand: "پاکشوما",
        Weight: "",
        priceReduction: "",
        Discount: "",
        price: 17410000,
        ProductFeatures: [
          {
            id: 58,
            type: "ایستاده",
            color: "سیلور",
            Capacity: "۱۴ نفره",
            dis: "قابلیت تنظیم زمان خشک کن و شستشو",
            sizePanel: "۸۵x۶۰x۶۰ سانتی متر",
            amountOfWind: "",
            CondenserSize: "",
            InnerPanelWeight: "",
            ExternalNnitWeight: "",
            TheVolumeOfTheInternalPanel: "",
            TheVolumeOfTheExternalUnit: "",
            Description: "",
          },
        ],
      },
      {
        id: 39,
        category: "لوازم برقی آشپزخانه",
        image: image34,
        title: "ماشین ظرفشویی MDF-۱۵۳۰۲S سیلور سری Josephine پاکشوما ۱۵ نفره",
        Brand: "پاکشوما",
        Weight: "",
        priceReduction: "",
        Discount: "",
        price: 17690000,
        ProductFeatures: [
          {
            id: 59,
            type: "ایستاده",
            color: "سیلور",
            Capacity: "۱۴ نفره",
            dis: "قابلیت تنظیم زمان خشک کن و شستشو",
            sizePanel: "۸۵x۶۰x۶۰ سانتی متر",
            amountOfWind: "",
            CondenserSize: "",
            InnerPanelWeight: "",
            ExternalNnitWeight: "",
            TheVolumeOfTheInternalPanel: "",
            TheVolumeOfTheExternalUnit: "",
            Description: "",
          },
        ],
      },
      {
        id: 40,
        category: "لوازم برقی آشپزخانه",
        image: image35,
        title: "ماشین لباسشویی TFB-۹۴۴۰۱ST سیلور سری K پاکشوما ۹ کیلوگرمی",
        Brand: "پاکشوما",
        Weight: "",
        priceReduction: "",
        Discount: "",
        price: 13856000,
        ProductFeatures: [
          {
            id: 60,
            type: " اتوماتیک",
            color: "سیلور",
            Capacity: "9 کیلوگرم",
            dis: "دارای ۱۶ برنامه شستشوی اصلی و ۶ برنامه کمکی",
            sizePanel: "",
            amountOfWind: "",
            CondenserSize: "",
            InnerPanelWeight: "",
            ExternalNnitWeight: "",
            TheVolumeOfTheInternalPanel: "",
            TheVolumeOfTheExternalUnit: "",
            Description: "",
          },
        ],
      },
      {
        id: 41,
        category: "لوازم برقی آشپزخانه",
        image: image36,
        title: "ماشین لباسشویی TFB-۸۵۴۰۲ST سیلور سری L پاکشوما ۸ کیلوگرمی",
        Brand: "پاکشوما",
        Weight: "",
        priceReduction: "",
        Discount: "",
        price: 13330000,
        ProductFeatures: [
          {
            id: 61,
            type: " اتوماتیک",
            color: "سیلور",
            Capacity: "۸ کیلوگرم",
            dis: "دارای ۱۶ برنامه شستشوی اصلی و ۴ برنامه کمکی",
            sizePanel: "",
            amountOfWind: "",
            CondenserSize: "",
            InnerPanelWeight: "",
            ExternalNnitWeight: "",
            TheVolumeOfTheInternalPanel: "",
            TheVolumeOfTheExternalUnit: "",
            Description: "",
          },
        ],
      },
      {
        id: 42,
        category: "لوازم برقی آشپزخانه",
        image: image37,
        title: "ماشین لباسشویی PWT-۸۵۷۳AJ سفید پاکشوما ۸.۵ کیلوگرمی",
        Brand: "پاکشوما",
        Weight: "",
        priceReduction: "",
        Discount: "",
        price: 3084000,
        ProductFeatures: [
          {
            id: 62,
            type: "نیمه اتوماتیک",
            color: "سفید",
            Capacity: "8.5 کیلوگرم",
            dis: "قابلیت تنظیم زمان خشک کن و شستشو",
            sizePanel: "",
            amountOfWind: "",
            CondenserSize: "",
            InnerPanelWeight: "",
            ExternalNnitWeight: "",
            TheVolumeOfTheInternalPanel: "",
            TheVolumeOfTheExternalUnit: "",
            Description: "",
          },
        ],
      },
    ],
  },
];
