import image1 from "../../assets/Images/ImageDataBase/Cosmetics/image1.jpg";
import image2 from "../../assets/Images/ImageDataBase/Cosmetics/image2.jpg";
import image3 from "../../assets/Images/ImageDataBase/Cosmetics/image3.jpg";
import image4 from "../../assets/Images/ImageDataBase/Cosmetics/image4.jpg";
import image5 from "../../assets/Images/ImageDataBase/Cosmetics/image5.jpg";
import image6 from "../../assets/Images/ImageDataBase/Cosmetics/image6.jpg";
import image7 from "../../assets/Images/ImageDataBase/Cosmetics/image7.jpg";
import image8 from "../../assets/Images/ImageDataBase/Cosmetics/image8.jpg";
import image9 from "../../assets/Images/ImageDataBase/Cosmetics/image9.jpg";
import image10 from "../../assets/Images/ImageDataBase/Cosmetics/image10.jpg";
import image11 from "../../assets/Images/ImageDataBase/Cosmetics/image11.jpg";
import image12 from "../../assets/Images/ImageDataBase/Cosmetics/image12.jpg";
import image13 from "../../assets/Images/ImageDataBase/Cosmetics/image13.jpg";
import image14 from "../../assets/Images/ImageDataBase/Cosmetics/image14.jpg";
import image15 from "../../assets/Images/ImageDataBase/Cosmetics/image15.jpg";
import image16 from "../../assets/Images/ImageDataBase/Cosmetics/image16.jpg";
import image17 from "../../assets/Images/ImageDataBase/Cosmetics/image17.jpg";
import image18 from "../../assets/Images/ImageDataBase/Cosmetics/image18.jpg";
import image19 from "../../assets/Images/ImageDataBase/Cosmetics/image19.jpg";
import image20 from "../../assets/Images/ImageDataBase/Cosmetics/image20.jpg";
import image21 from "../../assets/Images/ImageDataBase/Cosmetics/image21.jpg";
import image22 from "../../assets/Images/ImageDataBase/Cosmetics/image22.jpg";
import image23 from "../../assets/Images/ImageDataBase/Cosmetics/image23.jpg";
import image24 from "../../assets/Images/ImageDataBase/Cosmetics/image24.jpg";
import image25 from "../../assets/Images/ImageDataBase/Cosmetics/image25.jpg";
import image26 from "../../assets/Images/ImageDataBase/Cosmetics/image26.jpg";
import image27 from "../../assets/Images/ImageDataBase/Cosmetics/image27.jpg";
import image28 from "../../assets/Images/ImageDataBase/Cosmetics/image28.jpg";
import image29 from "../../assets/Images/ImageDataBase/Cosmetics/image29.jpg";
import image30 from "../../assets/Images/ImageDataBase/Cosmetics/image30.jpg";
import image31 from "../../assets/Images/ImageDataBase/Cosmetics/image31.jpg";
import image32 from "../../assets/Images/ImageDataBase/Cosmetics/image32.jpg";
import image33 from "../../assets/Images/ImageDataBase/Cosmetics/image33.jpg";
import image34 from "../../assets/Images/ImageDataBase/Cosmetics/image34.jpg";
import image35 from "../../assets/Images/ImageDataBase/Cosmetics/image35.jpg";
import image36 from "../../assets/Images/ImageDataBase/Cosmetics/image36.jpg";
import image37 from "../../assets/Images/ImageDataBase/Cosmetics/image37.jpg";
import image38 from "../../assets/Images/ImageDataBase/Cosmetics/image38.jpg";
import image39 from "../../assets/Images/ImageDataBase/Cosmetics/image39.jpg";
import image40 from "../../assets/Images/ImageDataBase/Cosmetics/image40.jpg";
import image41 from "../../assets/Images/ImageDataBase/Cosmetics/image41.jpg";
import image42 from "../../assets/Images/ImageDataBase/Cosmetics/image42.jpg";
import image43 from "../../assets/Images/ImageDataBase/Cosmetics/image43.jpg";
import image44 from "../../assets/Images/ImageDataBase/Cosmetics/image44.jpg";
import image45 from "../../assets/Images/ImageDataBase/Cosmetics/image45.jpg";
export const DataBaseCosmetics = [
  {
    id: 2,
    name: "",
    categories: [
      "محصولات آرایشی",
      "بهداشت و مراقبت صورت",
      "شامپو و مراقبت مو",
      "آرایش مو",
      "بهداشت و مراقبت بدن",
      "بهداشت دهان",
      "اصلاح صورت وبدن",
    ],
    cosmetics: [
      {
        id: 1,
        category: "محصولات آرایشی",
        image: image1,
        title: "مرطوب کننده لب Intense Moisturizing هیدرودرم ۴.۵ گرمی",
        Weight: "4.5گرم ",
        priceReduction: "49,034",
        Discount: "20%",
        Price: "39,و228",
        Brand: "هیدرودرم",
        Seller: "هایپراستار",
        ProductFeatures: [
          {
            id: 47,
            type: "جامد",
            skinType: "انواع پوست",
            effect: "براق",
            Durability: "بالا",
            dis: "حاوی ویتامین A و E و دکسپانتنول",
          },
        ],
      },
      {
        id: 2,
        category: "محصولات آرایشی",
        image: image2,
        title: "موچین انبری Classic زینگر",
        Weight: "",
        priceReduction: "",
        Discount: "",
        Price: "2,721",
        Brand: "زینگر",
        Seller: "هایپراستار",
        ProductFeatures: [{}],
      },
      {
        id: 3,
        category: "محصولات آرایشی",
        image: image3,
        title: "پنبه توپک گل پر ۱۰۰ گرمی",
        Weight: "100 گرم",
        priceReduction: "",
        Discount: "",
        Price: "8,880",
        Brand: "گل پر",
        Seller: "هایپراستار",
        ProductFeatures: [
          {
            id: 48,
            type: "پنبه",
            skinType: "انواع پوست",
            effect: "براق",
            Durability: "بالا",
            dis: "قابل استفاده برای مصرف آرایشی و بهداشتی",
          },
        ],
      },
      {
        id: 4,
        category: "محصولات آرایشی",
        image: image4,
        title: "دستمال لاک پاک کن کامان ۴۵ عددی",
        Weight: "45 عدد",
        priceReduction: "128,000",
        Discount: "66%",
        Price: "43,520",
        Brand: "کامان",
        Seller: "هایپراستار",
        ProductFeatures: [
          {
            id: 49,
            type: "پد",
            skinType: "انواع پوست",
            effect: "براق",
            Durability: "بالا",
            dis: "جلوگیری از شکنندگی، کدری، زردی و لایه لایه شدن ناخن ها",
          },
        ],
      },
      {
        id: 5,
        category: "محصولات آرایشی",
        image: image5,
        title: "دستمال لاک پاک کن یونی لد ۱۰ عددی",
        Weight: "10عدد ",
        priceReduction: "",
        Discount: "",
        Price: "13,800",
        Brand: "یونی لد",
        Seller: "هایپر استار",
        ProductFeatures: [
          {
            id: 50,
            type: "دستمال",
            skinType: "انواع پوست",
            effect: "براق",
            Durability: "بالا",
            dis: "حاوی گلیسیرین و ویتامین E",
          },
        ],
      },
      {
        id: 6,
        category: "محصولات آرایشی",
        image: image6,
        title: "ناخن گیر سایز کوچک",
        Weight: "",
        priceReduction: "",
        Discount: "",
        Price: "111,943",
        Brand: "بدون برند",
        Seller: "هایپر استار",
        ProductFeatures: [{}],
      },
      {
        id: 7,
        category: "محصولات آرایشی",
        image: image7,
        title: "ابر پنکیک ضخیم ۳ عددی",
        Weight: "3عدد ",
        priceReduction: "",
        Discount: "",
        Price: "64,000",
        Brand: "بدون برند",
        Seller: "هایپراستار",
        ProductFeatures: [{}],
      },
      {
        id: 8,
        category: "محصولات آرایشی",
        image: image8,
        title: "کرم پودر مایع فاقد چربی Natrual Rose سیترای ۴۰ میلی لیتری",
        Weight: "40 میلی لیتری",
        priceReduction: "",
        Discount: "",
        Price: "3,971",
        Brand: "سیترای",
        Seller: "هایپر استار",
        ProductFeatures: [
          {
            id: 51,
            type: "مایع",
            skinType: "چرب",
            effect: "براق",
            Durability: "بالا",
            dis: "حاوی تری اتوکسی کاپریلیل جهت دوام و ماندگاری بیشتر",
          },
        ],
      },
      {
        id: 9,
        category: "محصولات آرایشی",
        image: image9,
        title: "موچین انبری باریک کج زینگر",
        Weight: "",
        priceReduction: "",
        Discount: "",
        Price: "132,000",
        Brand: "زینگر",
        Seller: "هایپر استار",
        ProductFeatures: [{}],
      },
      {
        id: 10,
        category: "محصولات آرایشی",
        image: image10,
        title: "موچین انبری باریک براق زینگر",
        Weight: "",
        priceReduction: "",
        Discount: "",
        Price: "148,000",
        Brand: "زینگر",
        Seller: "هایپر استار",
        ProductFeatures: [
          {
            id: 52,
            type: "انبری",
            skinType: "فلزی",
            effect: "طلایی",
            Durability: "بالا",
            dis: "",
          },
        ],
      },
      {
        id: 11,
        category: "محصولات آرایشی",
        image: image11,
        title: "دستمال لاک پاک کن نینو ۴۵ عددی",
        Weight: "45عددی",
        priceReduction: "57,900",
        Discount: "20%",
        Price: "46,320",
        Brand: "نینو",
        Seller: "هایپر استار",
        ProductFeatures: [
          {
            id: 53,
            type: "دستمال",
            skinType: " بطری پلاستیکی",
            effect: "سفید",
            Durability: "بالا",
            dis: "مناسب انواع ناخن",
          },
        ],
      },
      {
        id: 12,
        category: "بهداشت و مراقبت صورت",
        image: image12,
        title: "ضد آفتاب رنگی SPF۴۶ آردن ۵۰ میلی لیتری",
        Weight: "50 میلی لیتری",
        priceReduction: "82,615",
        Discount: "14%",
        Price: "71,049",
        Brand: "آردن",
        Seller: "هایپر استار",
        ProductFeatures: [
          {
            id: 54,
            type: "ضد آفتاب",
            skinType: "معمولی و حساس",
            effect: "سفید",
            Durability: "بالا",
            dis: "حاوی رنگدانه های معدنی (Pigments) جهت هماهنگی با رنگ طبیعی پوست",
          },
        ],
      },
      {
        id: 13,
        category: "بهداشت و مراقبت صورت",
        image: image13,
        title: "ضد آفتاب رنگی Light Beige آردن ۵۰ میلی لیتری",
        Weight: "50 میلی لیتری",
        priceReduction: "82,346",
        Discount: "20%",
        Price: "65,877",
        Brand: "آردن",
        Seller: "هایپر استار",
        ProductFeatures: [
          {
            id: 55,
            type: "ضد لک",
            skinType: "انواع پوست",
            effect: "سفید",
            Durability: "بالا",
            dis: "محافظت پوست در مقابل اشعه‌های مضر خورشید",
          },
        ],
      },
      {
        id: 14,
        category: "بهداشت و مراقبت صورت",
        image: image14,
        title: "ماسک صورت Aloe Vera رینوزیت ۱۰۰ میلی لیتری",
        Weight: "100 میلی لیتری",
        priceReduction: "38,000",
        Discount: "30%",
        Price: "26,600",
        Brand: "رینوزیت",
        Seller: "هایپر استار",
        ProductFeatures: [{
          id: 56,
          type: "روشن کننده صورت",
          skinType: "انواع پوست",
          effect: "سفید",
          Durability: "بالا",
          dis: "شاداب کننده پوست",
        }],
      },
      {
        id: 15,
        category: "بهداشت و مراقبت صورت",
        image: image15,
        title: "کرم دور چشم ضد چروک هیدرودرم ۲۰ میلی لیتری",
        Weight: "20 میلی لیتری",
        priceReduction: "157,119",
        Discount: "20%",
        Price: "125,696",
        Brand: "آردن",
        Seller: "هایپر استار",
        ProductFeatures: [{
          id: 57,
          type: "ضد چروک",
          skinType: "حساس",
          effect: "سفید",
          Durability: "بالا",
          dis: "رفع چین و چروک و کاهش سیاهی اطراف چشم",
        }],
      },
      {
        id: 16,
        category: "بهداشت و مراقبت صورت",
        image: image16,
        title: "ژل پس از سوختگی آلوئه ورا سی گل ۲۵۰ میلی لیتری",
        Weight: "250 میلی لیتری",
        priceReduction: "79,000",
        Discount: "15%",
        Price: "67,150",
        Brand: "سی گل",
        Seller: "هایپر استار",
        ProductFeatures: [{
          id: 58,
          type: " ژل",
          skinType: "بدن",
          effect: "آلوئه ورا",
          Durability: "بالا",
          dis: "کاهش سوزش، خارش و قرمزی پوست پس از آفتاب سوختگی",
        }],
      },
      {
        id: 17,
        category: "بهداشت و مراقبت صورت",
        image: image17,
        title: "کرم روشن کننده AHA ۱۰٪ سینره ۴۰ میلی لیتری",
        Weight: "40 میلی لیتری",
        priceReduction: "88,000",
        Discount: "15%",
        Price: "74,800",
        Brand: "سیزه",
        Seller: "هایپر استار",
        ProductFeatures: [{
          id: 59,
          type: " کرم",
          skinType: "بدن",
          effect: "آلوئه ورا",
          Durability: "بالا",
          dis: "کاهش سوزش، خارش و قرمزی پوست پس از آفتاب سوختگی",
        }],
      },
      {
        id: 18,
        category: "بهداشت و مراقبت صورت",
        image: image18,
        title: "کرم ضد آکنه Dermaline آردن ۵۰ میلی لیتری",
        Weight: "50 میلی لیتری",
        priceReduction: "73,894",
        Discount: "14%",
        Price: "63,549",
        Brand: "آردن",
        Seller: "هایپر استار",
        ProductFeatures: [{
          id: 60,
          type: "ضد آکنه",
          skinType: "چرب و آکنه دار",
          effect: "آلوئه ورا",
          Durability: "بالا",
          dis: "کاهش سوزش، خارش و قرمزی پوست پس از آفتاب سوختگی",
        }],
      },
      {
        id: 19,
        category: "بهداشت و مراقبت صورت",
        image: image19,
        title: "",
        Weight: "",
        priceReduction: "",
        Discount: "",
        Price: "",
        Brand: "",
        Seller: "",
        ProductFeatures: [{}],
      },
      {
        id: 20,
        category: "بهداشت و مراقبت صورت",
        image: image20,
        title: "",
        Weight: "",
        priceReduction: "",
        Discount: "",
        Price: "",
        Brand: "",
        Seller: "",
        ProductFeatures: [{}],
      },
      {
        id: 21,
        category: "بهداشت و مراقبت صورت",
        image: image21,
        title: "",
        Weight: "",
        priceReduction: "",
        Discount: "",
        Price: "",
        Brand: "",
        Seller: "",
        ProductFeatures: [{}],
      },
      {
        id: 22,
        category: "بهداشت و مراقبت صورت",
        image: image22,
        title: "",
        Weight: "",
        priceReduction: "",
        Discount: "",
        Price: "",
        Brand: "",
        Seller: "",
        ProductFeatures: [{}],
      },
      {
        id: 23,
        category: "",
        image: "",
        title: "",
        Weight: "",
        priceReduction: "",
        Discount: "",
        Price: "",
        Brand: "",
        Seller: "",
        ProductFeatures: [{}],
      },
      {
        id: 24,
        category: "",
        image: "",
        title: "",
        Weight: "",
        priceReduction: "",
        Discount: "",
        Price: "",
        Brand: "",
        Seller: "",
        ProductFeatures: [{}],
      },
      {
        id: 25,
        category: "",
        image: "",
        title: "",
        Weight: "",
        priceReduction: "",
        Discount: "",
        Price: "",
        Brand: "",
        Seller: "",
        ProductFeatures: [{}],
      },
      {
        id: 26,
        category: "",
        image: "",
        title: "",
        Weight: "",
        priceReduction: "",
        Discount: "",
        Price: "",
        Brand: "",
        Seller: "",
        ProductFeatures: [{}],
      },
      {
        id: 27,
        category: "",
        image: "",
        title: "",
        Weight: "",
        priceReduction: "",
        Discount: "",
        Price: "",
        Brand: "",
        Seller: "",
        ProductFeatures: [{}],
      },
      {
        id: 28,
        category: "",
        image: "",
        title: "",
        Weight: "",
        priceReduction: "",
        Discount: "",
        Price: "",
        Brand: "",
        Seller: "",
        ProductFeatures: [{}],
      },
      {
        id: 29,
        category: "",
        image: "",
        title: "",
        Weight: "",
        priceReduction: "",
        Discount: "",
        Price: "",
        Brand: "",
        Seller: "",
        ProductFeatures: [{}],
      },
      {
        id: 30,
        category: "",
        image: "",
        title: "",
        Weight: "",
        priceReduction: "",
        Discount: "",
        Price: "",
        Brand: "",
        Seller: "",
        ProductFeatures: [{}],
      },
      {
        id: 31,
        category: "",
        image: "",
        title: "",
        Weight: "",
        priceReduction: "",
        Discount: "",
        Price: "",
        Brand: "",
        Seller: "",
        ProductFeatures: [{}],
      },
      {
        id: 32,
        category: "",
        image: "",
        title: "",
        Weight: "",
        priceReduction: "",
        Discount: "",
        Price: "",
        Brand: "",
        Seller: "",
        ProductFeatures: [{}],
      },
      {
        id: 33,
        category: "",
        image: "",
        title: "",
        Weight: "",
        priceReduction: "",
        Discount: "",
        Price: "",
        Brand: "",
        Seller: "",
        ProductFeatures: [{}],
      },
      {
        id: 34,
        category: "",
        image: "",
        title: "",
        Weight: "",
        priceReduction: "",
        Discount: "",
        Price: "",
        Brand: "",
        Seller: "",
        ProductFeatures: [{}],
      },
      {
        id: 35,
        category: "",
        image: "",
        title: "",
        Weight: "",
        priceReduction: "",
        Discount: "",
        Price: "",
        Brand: "",
        Seller: "",
        ProductFeatures: [{}],
      },
      {
        id: 36,
        category: "",
        image: "",
        title: "",
        Weight: "",
        priceReduction: "",
        Discount: "",
        Price: "",
        Brand: "",
        Seller: "",
        ProductFeatures: [{}],
      },
      {
        id: 37,
        category: "",
        image: "",
        title: "",
        Weight: "",
        priceReduction: "",
        Discount: "",
        Price: "",
        Brand: "",
        Seller: "",
        ProductFeatures: [{}],
      },
      {
        id: 38,
        category: "",
        image: "",
        title: "",
        Weight: "",
        priceReduction: "",
        Discount: "",
        Price: "",
        Brand: "",
        Seller: "",
        ProductFeatures: [{}],
      },
      {
        id: 39,
        category: "",
        image: "",
        title: "",
        Weight: "",
        priceReduction: "",
        Discount: "",
        Price: "",
        Brand: "",
        Seller: "",
        ProductFeatures: [{}],
      },
      {
        id: 40,
        category: "",
        image: "",
        title: "",
        Weight: "",
        priceReduction: "",
        Discount: "",
        Price: "",
        Brand: "",
        Seller: "",
        ProductFeatures: [{}],
      },
      {
        id: 41,
        category: "",
        image: "",
        title: "",
        Weight: "",
        priceReduction: "",
        Discount: "",
        Price: "",
        Brand: "",
        Seller: "",
        ProductFeatures: [{}],
      },
      {
        id: 42,
        category: "",
        image: "",
        title: "",
        Weight: "",
        priceReduction: "",
        Discount: "",
        Price: "",
        Brand: "",
        Seller: "",
        ProductFeatures: [{}],
      },
      {
        id: 43,
        category: "",
        image: "",
        title: "",
        Weight: "",
        priceReduction: "",
        Discount: "",
        Price: "",
        Brand: "",
        Seller: "",
        ProductFeatures: [{}],
      },
      {
        id: 44,
        category: "",
        image: "",
        title: "",
        Weight: "",
        priceReduction: "",
        Discount: "",
        Price: "",
        Brand: "",
        Seller: "",
        ProductFeatures: [{}],
      },
      {
        id: 45,
        category: "",
        image: "",
        title: "",
        Weight: "",
        priceReduction: "",
        Discount: "",
        Price: "",
        Brand: "",
        Seller: "",
        ProductFeatures: [{}],
      },
      {
        id: 46,
        category: "",
        image: "",
        title: "",
        Weight: "",
        priceReduction: "",
        Discount: "",
        Price: "",
        Brand: "",
        Seller: "",
        ProductFeatures: [{}],
      },
    ],
  },
];
