import image1 from "../../assets/Images/ImageDataBase/Cosmetics/image1.jpg";
import image2 from "../../assets/Images/ImageDataBase/Cosmetics/image2.jpg";
import image3 from "../../assets/Images/ImageDataBase/Cosmetics/image3.jpg";
import image4 from "../../assets/Images/ImageDataBase/Cosmetics/image4.jpg";
import image5 from "../../assets/Images/ImageDataBase/Cosmetics/image5.jpg";
import image6 from "../../assets/Images/ImageDataBase/Cosmetics/image6.jpg";
import image7 from "../../assets/Images/ImageDataBase/Cosmetics/image7.jpg";
import image8 from "../../assets/Images/ImageDataBase/Cosmetics/image8.jpg";
import image9 from "../../assets/Images/ImageDataBase/Cosmetics/image9.jpg";
import image10 from "../../assets/Images/ImageDataBase/Cosmetics/image10.jpg";
import image11 from "../../assets/Images/ImageDataBase/Cosmetics/image11.jpg";
import image12 from "../../assets/Images/ImageDataBase/Cosmetics/image12.jpg";
import image13 from "../../assets/Images/ImageDataBase/Cosmetics/image13.jpg";
import image14 from "../../assets/Images/ImageDataBase/Cosmetics/image14.jpg";
import image15 from "../../assets/Images/ImageDataBase/Cosmetics/image15.jpg";
import image16 from "../../assets/Images/ImageDataBase/Cosmetics/image16.jpg";
import image17 from "../../assets/Images/ImageDataBase/Cosmetics/image17.jpg";
import image18 from "../../assets/Images/ImageDataBase/Cosmetics/image18.jpg";
import image19 from "../../assets/Images/ImageDataBase/Cosmetics/image19.jpg";
import image20 from "../../assets/Images/ImageDataBase/Cosmetics/image20.jpg";
import image21 from "../../assets/Images/ImageDataBase/Cosmetics/image21.jpg";
import image22 from "../../assets/Images/ImageDataBase/Cosmetics/image22.jpg";
import image23 from "../../assets/Images/ImageDataBase/Cosmetics/image23.jpg";
import image24 from "../../assets/Images/ImageDataBase/Cosmetics/image24.jpg";
import image25 from "../../assets/Images/ImageDataBase/Cosmetics/image25.jpg";
import image26 from "../../assets/Images/ImageDataBase/Cosmetics/image26.jpg";
import image27 from "../../assets/Images/ImageDataBase/Cosmetics/image27.jpg";
import image28 from "../../assets/Images/ImageDataBase/Cosmetics/image28.jpg";
import image29 from "../../assets/Images/ImageDataBase/Cosmetics/image29.jpg";
import image30 from "../../assets/Images/ImageDataBase/Cosmetics/image30.jpg";
import image31 from "../../assets/Images/ImageDataBase/Cosmetics/image31.jpg";
import image32 from "../../assets/Images/ImageDataBase/Cosmetics/image32.jpg";
import image33 from "../../assets/Images/ImageDataBase/Cosmetics/image33.jpg";
import image34 from "../../assets/Images/ImageDataBase/Cosmetics/image34.jpg";
import image35 from "../../assets/Images/ImageDataBase/Cosmetics/image35.jpg";
import image36 from "../../assets/Images/ImageDataBase/Cosmetics/image36.jpg";
import image37 from "../../assets/Images/ImageDataBase/Cosmetics/image37.jpg";
import image38 from "../../assets/Images/ImageDataBase/Cosmetics/image38.jpg";
import image39 from "../../assets/Images/ImageDataBase/Cosmetics/image39.jpg";
import image40 from "../../assets/Images/ImageDataBase/Cosmetics/image40.jpg";
import image41 from "../../assets/Images/ImageDataBase/Cosmetics/image41.jpg";
import image42 from "../../assets/Images/ImageDataBase/Cosmetics/image42.jpg";
import image43 from "../../assets/Images/ImageDataBase/Cosmetics/image43.jpg";
import image44 from "../../assets/Images/ImageDataBase/Cosmetics/image44.jpg";
import image45 from "../../assets/Images/ImageDataBase/Cosmetics/image45.jpg";
export const DataBaseCosmetics = [
  {
    id: 2,
    name: "",
    categories: [
      "محصولات آرایشی",
      "بهداشت و مراقبت صورت",
      "شامپو و مراقبت مو",
      "آرایش مو",
      "بهداشت و مراقبت بدن",
      "بهداشت دهان",
      "اصلاح صورت وبدن",
    ],
    cosmetics: [
      {
        id: 1,
        category: "محصولات آرایشی",
        image: image1,
        title: "مرطوب کننده لب Intense Moisturizing هیدرودرم ۴.۵ گرمی",
        Weight: "4.5گرم ",
        priceReduction: "49,034",
        Discount: "20%",
        Price: "39,و228",
        Brand: "هیدرودرم",
        Seller: "هایپراستار",
        ProductFeatures: [
          {
            id: 47,
            type: "جامد",
            skinType: "انواع پوست",
            effect: "براق",
            Durability: "بالا",
            dis: "حاوی ویتامین A و E و دکسپانتنول",
          },
        ],
      },
      {
        id: 2,
        category: "محصولات آرایشی",
        image: image2,
        title: "موچین انبری Classic زینگر",
        Weight: "",
        priceReduction: "",
        Discount: "",
        Price: "2,721",
        Brand: "زینگر",
        Seller: "هایپراستار",
        ProductFeatures: [{}],
      },
      {
        id: 3,
        category: "محصولات آرایشی",
        image: image3,
        title: "پنبه توپک گل پر ۱۰۰ گرمی",
        Weight: "100 گرم",
        priceReduction: "",
        Discount: "",
        Price: "8,880",
        Brand: "گل پر",
        Seller: "هایپراستار",
        ProductFeatures: [
          {
            id: 48,
            type: "پنبه",
            skinType: "انواع پوست",
            effect: "براق",
            Durability: "بالا",
            dis: "قابل استفاده برای مصرف آرایشی و بهداشتی",
          },
        ],
      },
      {
        id: 4,
        category: "محصولات آرایشی",
        image: image4,
        title: "دستمال لاک پاک کن کامان ۴۵ عددی",
        Weight: "45 عدد",
        priceReduction: "128,000",
        Discount: "66%",
        Price: "43,520",
        Brand: "کامان",
        Seller: "هایپراستار",
        ProductFeatures: [
          {
            id: 49,
            type: "پد",
            skinType: "انواع پوست",
            effect: "براق",
            Durability: "بالا",
            dis: "جلوگیری از شکنندگی، کدری، زردی و لایه لایه شدن ناخن ها",
          },
        ],
      },
      {
        id: 5,
        category: "محصولات آرایشی",
        image: image5,
        title: "دستمال لاک پاک کن یونی لد ۱۰ عددی",
        Weight: "10عدد ",
        priceReduction: "",
        Discount: "",
        Price: "13,800",
        Brand: "یونی لد",
        Seller: "هایپر استار",
        ProductFeatures: [
          {
            id: 50,
            type: "دستمال",
            skinType: "انواع پوست",
            effect: "براق",
            Durability: "بالا",
            dis: "حاوی گلیسیرین و ویتامین E",
          },
        ],
      },
      {
        id: 6,
        category: "محصولات آرایشی",
        image: image6,
        title: "ناخن گیر سایز کوچک",
        Weight: "",
        priceReduction: "",
        Discount: "",
        Price: "111,943",
        Brand: "بدون برند",
        Seller: "هایپر استار",
        ProductFeatures: [{}],
      },
      {
        id: 7,
        category: "محصولات آرایشی",
        image: image7,
        title: "ابر پنکیک ضخیم ۳ عددی",
        Weight: "3عدد ",
        priceReduction: "",
        Discount: "",
        Price: "64,000",
        Brand: "بدون برند",
        Seller: "هایپراستار",
        ProductFeatures: [{}],
      },
      {
        id: 8,
        category: "محصولات آرایشی",
        image: image8,
        title: "کرم پودر مایع فاقد چربی Natrual Rose سیترای ۴۰ میلی لیتری",
        Weight: "40 میلی لیتری",
        priceReduction: "",
        Discount: "",
        Price: "3,971",
        Brand: "سیترای",
        Seller: "هایپر استار",
        ProductFeatures: [
          {
            id: 51,
            type: "مایع",
            skinType: "چرب",
            effect: "براق",
            Durability: "بالا",
            dis: "حاوی تری اتوکسی کاپریلیل جهت دوام و ماندگاری بیشتر",
          },
        ],
      },
      {
        id: 9,
        category: "محصولات آرایشی",
        image: image9,
        title: "موچین انبری باریک کج زینگر",
        Weight: "",
        priceReduction: "",
        Discount: "",
        Price: "132,000",
        Brand: "زینگر",
        Seller: "هایپر استار",
        ProductFeatures: [{}],
      },
      {
        id: 10,
        category: "محصولات آرایشی",
        image: image10,
        title: "موچین انبری باریک براق زینگر",
        Weight: "",
        priceReduction: "",
        Discount: "",
        Price: "148,000",
        Brand: "زینگر",
        Seller: "هایپر استار",
        ProductFeatures: [
          {
            id: 52,
            type: "انبری",
            skinType: "فلزی",
            effect: "طلایی",
            Durability: "بالا",
            dis: "",
          },
        ],
      },
      {
        id: 11,
        category: "محصولات آرایشی",
        image: image11,
        title: "دستمال لاک پاک کن نینو ۴۵ عددی",
        Weight: "45عددی",
        priceReduction: "57,900",
        Discount: "20%",
        Price: "46,320",
        Brand: "نینو",
        Seller: "هایپر استار",
        ProductFeatures: [
          {
            id: 53,
            type: "دستمال",
            skinType: " بطری پلاستیکی",
            effect: "سفید",
            Durability: "بالا",
            dis: "مناسب انواع ناخن",
          },
        ],
      },
      {
        id: 12,
        category: "بهداشت و مراقبت صورت",
        image: image12,
        title: "ضد آفتاب رنگی SPF۴۶ آردن ۵۰ میلی لیتری",
        Weight: "50 میلی لیتری",
        priceReduction: "82,615",
        Discount: "14%",
        Price: "71,049",
        Brand: "آردن",
        Seller: "هایپر استار",
        ProductFeatures: [
          {
            id: 54,
            type: "ضد آفتاب",
            skinType: "معمولی و حساس",
            effect: "سفید",
            Durability: "بالا",
            dis: "حاوی رنگدانه های معدنی (Pigments) جهت هماهنگی با رنگ طبیعی پوست",
          },
        ],
      },
      {
        id: 13,
        category: "بهداشت و مراقبت صورت",
        image: image13,
        title: "ضد آفتاب رنگی Light Beige آردن ۵۰ میلی لیتری",
        Weight: "50 میلی لیتری",
        priceReduction: "82,346",
        Discount: "20%",
        Price: "65,877",
        Brand: "آردن",
        Seller: "هایپر استار",
        ProductFeatures: [
          {
            id: 55,
            type: "ضد لک",
            skinType: "انواع پوست",
            effect: "سفید",
            Durability: "بالا",
            dis: "محافظت پوست در مقابل اشعه‌های مضر خورشید",
          },
        ],
      },
      {
        id: 14,
        category: "بهداشت و مراقبت صورت",
        image: image14,
        title: "ماسک صورت Aloe Vera رینوزیت ۱۰۰ میلی لیتری",
        Weight: "100 میلی لیتری",
        priceReduction: "38,000",
        Discount: "30%",
        Price: "26,600",
        Brand: "رینوزیت",
        Seller: "هایپر استار",
        ProductFeatures: [
          {
            id: 56,
            type: "روشن کننده صورت",
            skinType: "انواع پوست",
            effect: "سفید",
            Durability: "بالا",
            dis: "شاداب کننده پوست",
          },
        ],
      },
      {
        id: 15,
        category: "بهداشت و مراقبت صورت",
        image: image15,
        title: "کرم دور چشم ضد چروک هیدرودرم ۲۰ میلی لیتری",
        Weight: "20 میلی لیتری",
        priceReduction: "157,119",
        Discount: "20%",
        Price: "125,696",
        Brand: "آردن",
        Seller: "هایپر استار",
        ProductFeatures: [
          {
            id: 57,
            type: "ضد چروک",
            skinType: "حساس",
            effect: "سفید",
            Durability: "بالا",
            dis: "رفع چین و چروک و کاهش سیاهی اطراف چشم",
          },
        ],
      },
      {
        id: 16,
        category: "بهداشت و مراقبت صورت",
        image: image16,
        title: "ژل پس از سوختگی آلوئه ورا سی گل ۲۵۰ میلی لیتری",
        Weight: "250 میلی لیتری",
        priceReduction: "79,000",
        Discount: "15%",
        Price: "67,150",
        Brand: "سی گل",
        Seller: "هایپر استار",
        ProductFeatures: [
          {
            id: 58,
            type: " ژل",
            skinType: "بدن",
            effect: "آلوئه ورا",
            Durability: "بالا",
            dis: "کاهش سوزش، خارش و قرمزی پوست پس از آفتاب سوختگی",
          },
        ],
      },
      {
        id: 17,
        category: "بهداشت و مراقبت صورت",
        image: image17,
        title: "کرم روشن کننده AHA ۱۰٪ سینره ۴۰ میلی لیتری",
        Weight: "40 میلی لیتری",
        priceReduction: "88,000",
        Discount: "15%",
        Price: "74,800",
        Brand: "سیزه",
        Seller: "هایپر استار",
        ProductFeatures: [
          {
            id: 59,
            type: " کرم",
            skinType: "بدن",
            effect: "آلوئه ورا",
            Durability: "بالا",
            dis: "کاهش سوزش، خارش و قرمزی پوست پس از آفتاب سوختگی",
          },
        ],
      },
      {
        id: 18,
        category: "بهداشت و مراقبت صورت",
        image: image18,
        title: "کرم ضد آکنه Dermaline آردن ۵۰ میلی لیتری",
        Weight: "50 میلی لیتری",
        priceReduction: "73,894",
        Discount: "14%",
        Price: "63,549",
        Brand: "آردن",
        Seller: "هایپر استار",
        ProductFeatures: [
          {
            id: 60,
            type: "ضد آکنه",
            skinType: "چرب و آکنه دار",
            effect: "آلوئه ورا",
            Durability: "بالا",
            dis: "کمک به رفع انواع آکنه و پیشگیری از ایجاد جوش",
          },
        ],
      },
      {
        id: 19,
        category: "بهداشت و مراقبت صورت",
        image: image19,
        title: "کرم سفت کننده صورت Professional سینره ۴۰ میلی لیتری",
        Weight: "40 میلی لیتر",
        priceReduction: "160,000",
        Discount: "15%",
        Price: "136,000",
        Brand: "سینره",
        Seller: "هایپر استار",
        ProductFeatures: [
          {
            id: 61,
            type: "لیفتینگ",
            skinType: "انواع پوست",
            effect: "صورت و گردن",
            Durability: "بالا",
            dis: "سفت کننده سریع و طولانی پوست",
          },
        ],
      },
      {
        id: 20,
        category: "بهداشت و مراقبت صورت",
        image: image20,
        title: " کرم مرطوب کننده Avocado Oil سوپکس ۲۵۰ میلی لیتری",
        Weight: "250 میلی لیتر",
        priceReduction: "59,900",
        Discount: "40%",
        Price: "35,940",
        Brand: "سوپکس",
        Seller: "هایپر استار",
        ProductFeatures: [
          {
            id: 62,
            type: "مرطوب کننده و آبرسان",
            skinType: "انواع پوست",
            effect: "صورت و گردن",
            Durability: "بالا",
            dis: "حاوی روغن آووکادو و حاوی ویتامین E",
          },
        ],
      },
      {
        id: 21,
        category: "بهداشت و مراقبت صورت",
        image: image21,
        title: "پد پاک کننده آرایش سون کویین ۸۰ عددی",
        Weight: "80 عددی",
        priceReduction: "43,500",
        Discount: "3%",
        Price: "42,195",
        Brand: "سون کویین",
        Seller: "هایپر استار",
        ProductFeatures: [
          {
            id: 63,
            type: " پد پاک کننده آرایش",
            skinType: "تهیه شده از کتان و پنبه 100 درصد خالص",
            effect: "بافت نرم و لطیف",
            Durability: "جذب بالا",
            dis: "لایه ضخیم و نرم بیرونی",
          },
        ],
      },
      {
        id: 22,
        category: "بهداشت و مراقبت صورت",
        image: image22,
        title: "ضد آفتاب رنگی Light Beige کاسمکولوژی ۵۰ میلی لیتری",
        Weight: "50 میلی لیتری",
        priceReduction: "",
        Discount: "",
        Price: "150,000",
        Brand: "کاسمکولوژی",
        Seller: "هایپر استار",
        ProductFeatures: [
          {
            id: 64,
            type: "ضد آفتاب",
            skinType: "انواع پوست",
            effect: "بافت نرم و لطیف",
            Durability: "جذب بالا",
            dis: "ترمیم کننده و جوان کننده پوست",
          },
        ],
      },
      {
        id: 23,
        category: "شامپو و مراقبت مو",
        image: image23,
        title: "کرم آبرسان مو Biotin+Zinc سری Water Bomb کامان ۴۰۰ میلی لیتری",
        Weight: "400 میلی لیتر",
        priceReduction: "121,000",
        Discount: "25%",
        Price: "90,750",
        Brand: "کامان",
        Seller: "هایپر استار",
        ProductFeatures: [
          {
            id: 65,
            type: "ژل کرم",
            skinType: "انوع مو",
            effect: "پوست و میوه انار",
            Durability: "جذب بالا",
            dis: "حاوی بیوتین و زینک و بپانتین",
          },
        ],
      },
      {
        id: 24,
        category: "شامپو و مراقبت مو",
        image: image24,
        title: "لوسیون تقویت مو آقایان سینره ۶۰ میلی لیتری",
        Weight: "60 میلی لیتری",
        priceReduction: "115,000",
        Discount: "2%",
        Price: "112,700",
        Brand: "سینره",
        Seller: "هایپر استار",
        ProductFeatures: [
          {
            id: 66,
            type: "لوسیون",
            skinType: "انوع مو",
            effect: "مخصوص افراد با الگوی ریزش مردانه",
            Durability: "جذب بالا",
            dis: "جلوگیری از ریزش مو و کمک به رویش مجدد مو",
          },
        ],
      },
      {
        id: 25,
        category: "شامپو و مراقبت مو",
        image: image25,
        title: "لوسیون بدون ابکشی Ice Cream Biscuit بیول ۲۵۰ میلی لیتری",
        Weight: "250 میلی لیتری",
        priceReduction: "",
        Discount: "",
        Price: "66,100",
        Brand: "بیول",
        Seller: "هایپر استار",
        ProductFeatures: [
          {
            id: 67,
            type: "مرطوب کننده",
            skinType: "انوع مو",
            effect: "ترمیم کننده و تغذیه کننده مو آسیب دیده",
            Durability: "جذب بالا",
            dis: "جلوگیری از ریزش مو و کمک به رویش مجدد محاوی روغن آرگان، هسته انگور، زیتون و عصاره جوانه گندم",
          },
        ],
      },
      {
        id: 26,
        category: "شامپو و مراقبت مو",
        image: image26,
        title:
          "لوسیون مو رنگ شده Chamomile & Amaranthus دیپ سنس ۲۰۰ میلی لیتری",
        Weight: "200 میلی لیتر",
        priceReduction: "",
        Discount: "",
        Price: "44,000",
        Brand: "سی گل",
        Seller: "هایپر استار",
        ProductFeatures: [
          {
            id: 68,
            type: "لوسیون مو",
            skinType: "رنگ شده و آسیب دیده",
            effect: "بابونه و دانه تاج خروس",
            Durability: "جذب بالا",
            dis: "بهبود شانه پذیری و جلوگیری از گره خوردگی موها",
          },
        ],
      },
      {
        id: 27,
        category: "شامپو و مراقبت مو",
        image: image27,
        title: "ماسک مو Revitalizing Rich کریستال ۵۰۰ میلی لیتری",
        Weight: "500 میلی لیتر",
        priceReduction: "155,000",
        Discount: "19%",
        Price: "125,550",
        Brand: "کریستال",
        Seller: "هایپر استار",
        ProductFeatures: [
          {
            id: 69,
            type: " احیا کننده",
            skinType: " انواع مو",
            effect: "بابونه و دانه تاج خروس",
            Durability: "جذب بالا",
            dis: "حاوی ترکیب اسیدهای چرب و سیلیکون",
          },
        ],
      },
      {
        id: 28,
        category: "شامپو و مراقبت مو",
        image: image28,
        title: "کرم مو تقویت کننده Golden Argan لیمپیو ۳۵۰ میلی لیتری",
        Weight: "350 میلی لیتر",
        priceReduction: "",
        Discount: "",
        Price: "90,040",
        Brand: "لیمپیو",
        Seller: "هایپر استار",
        ProductFeatures: [
          {
            id: 70,
            type: "  تقویت کننده",
            skinType: " انواع مو",
            effect: "تقویت کننده و نرم کنننده ساقه مو",
            Durability: "جذب بالا",
            dis: "حاوی پروویتامین B5 و گلیسرین",
          },
        ],
      },
      {
        id: 29,
        category: "شامپو و مراقبت مو",
        image: image29,
        title:
          "ماسک مو تثبیت کننده رنگ Revitalizing Stabilizer کریستال ۵۰۰ میلی لیتری",
        Weight: "500 میلی لیتر",
        priceReduction: "155,000",
        Discount: "19%",
        Price: "125,550",
        Brand: "کریستال",
        Seller: "هایپر استار",
        ProductFeatures: [
          {
            id: 71,
            type: " ترمیم کننده و تثبیت کننده رنگ مو",
            skinType: "  آسیب دیده و رنگ شده",
            effect: "تقویت کننده و نرم کنننده ساقه مو",
            Durability: "جذب بالا",
            dis: "لطیف و درخشان کننده",
          },
        ],
      },
      {
        id: 30,
        category: "شامپو و مراقبت مو",
        image: image30,
        title: "سرم مراقبت مو بیول ۸۰ میلی لیتری",
        Weight: "80 میلی لیتری",
        priceReduction: "135,400",
        Discount: "25%",
        Price: "101,550",
        Brand: "بیول",
        Seller: "هایپر استار",
        ProductFeatures: [
          {
            id: 72,
            type: " سرم",
            skinType: " رنگ شده و آسیب دیده",
            effect: "روغن سبوس برنج، روغن هسته انگور",
            Durability: "جذب بالا",
            dis: "ترمیم کننده میان بافت های سلولی مو",
          },
        ],
      },
      {
        id: 31,
        category: "شامپو و مراقبت مو",
        image: image31,
        title: "کرم ژل مو Aloevera تاپ شاپ ۲۰۰ میلی لیتری",
        Weight: "200 میلی لیتری",
        priceReduction: "",
        Discount: "",
        Price: "72,600",
        Brand: "تاپ شاپ",
        Seller: "هایپر استار",
        ProductFeatures: [
          {
            id: 72,
            type: " کرم ژل",
            skinType: "معمولی، زخیم و زبر",
            effect: "حاوی عصاره های آلوئه ورا و روغن جوجوبا",
            Durability: "جذب بالا",
            dis: "مانع ایجاد پوسته و سفیدک روی موها",
          },
        ],
      },
      {
        id: 32,
        category: "شامپو و مراقبت مو",
        image: image32,
        title: "اسپری مو دو فاز Aloe Vera بیول ۲۵۰ میلی لیتری",
        Weight: "250 میلی لیتری",
        priceReduction: "",
        Discount: "",
        Price: "99,000",
        Brand: "بیول",
        Seller: "هایپر استار",
        ProductFeatures: [
          {
            id: 73,
            type: " اسپری دو فاز",
            skinType: "رنگ شده و آسیب دیده",
            effect: "ترمیم کننده و ضد ریزش",
            Durability: "جذب بالا",
            dis: "حاوی کراتین هیدرولیز شده برای احیای مجدد کورتکس مو و محافظت از مو در برابر آسیب‌های محیطی و حرارت",
          },
        ],
      },
      {
        id: 33,
        category: "شامپو و مراقبت مو",
        image: image33,
        title: "کرم مو ترمیم کننده Hot Brunette فولیکا ۲۰۰ میلی لیتری",
        Weight: "200 میلی لیتری",
        priceReduction: "90,646",
        Discount: "19%",
        Price: "73,424",
        Brand: "فولیکا",
        Seller: "هایپر استار",
        ProductFeatures: [
          {
            id: 73,
            type: " کرم مو",
            skinType: "رنگ شده و موهای قهوه ای",
            effect: "افزایش انعطاف پذیری مو",
            Durability: "جذب بالا",
            dis: "درخشان و براق کننده مو",
          },
        ],
      },
      {
        id: 34,
        category: "آرایش مو",
        image: image34,
        title: "واکس مو Garlic تاپ شاپ ۲۰۰ میلی لیتری",
        Weight: "200 میلی لیتری",
        priceReduction: "",
        Discount: "",
        Price: "58,700",
        Brand: "تاپ شاپ",
        Seller: "هایپر استارت",
        ProductFeatures: [
          {
            id: 74,
            type: " ژل",
            skinType: "انواع مو",
            effect: "افزایش انعطاف پذیری مو",
            Durability: "جذب بالا",
            dis: "بدون اثر سفیدی روی مو",
          },
        ],
      },
      {
        id: 35,
        category: "آرایش مو",
        image: image35,
        title: "کرم بی‌ رنگ کننده سی گل ۳۰ و ۶۰ میلی لیتری ۶۰ میلی لیتری",
        Weight: "60 میلی لیتر",
        priceReduction: "75,000",
        Discount: "19%",
        Price: "60,750",
        Brand: "سی گل",
        Seller: "هایپر استار",
        ProductFeatures: [
          {
            id: 75,
            type: " دکلره",
            skinType: "انواع پوست",
            effect: "صورت و بدن",
            Durability: "جذب بالا",
            dis: "روشن کننده",
          },
        ],
      },
      {
        id: 36,
        category: "آرایش مو",
        image: image36,
        title: "ژل حالت دهنده مو ویتامینه سینره ۱۵۰ میلی لیتری",
        Weight: "150 میلی لیتری",
        priceReduction: "45,000",
        Discount: "15%",
        Price: "38,250",
        Brand: "سینره",
        Seller: "هایپر استار",
        ProductFeatures: [
          {
            id: 76,
            type: " ژل",
            skinType: "انواع مو",
            effect: "افزایش انعطاف پذیری مو",
            Durability: "جذب بالا",
            dis: "حفظ حالت دلخواه مو به مدت طولانی",
          },
        ],
      },
      {
        id: 37,
        category: "آرایش مو",
        image: image37,
        title: "برس مو تخت بیضی بزرگ Tress Up بیول",
        Weight: "",
        priceReduction: "",
        Discount: "",
        Price: "66,015",
        Brand: "بیول",
        Seller: "هایپر استار",
        ProductFeatures: [
          {
            id: 78,
            type: " برس تخت",
            skinType: "انواع مو",
            effect: "صاف کننده مو برای انواع مو کوتاه و بلند",
            Durability: "جذب بالا",
            dis: "دارای پین های پلاستیکی آنتی استاتیک گرد جهت باز کردن گره‌ های مو",
          },
        ],
      },
      {
        id: 38,
        category: "آرایش مو",
        image: image38,
        title: "واکس مو کریستال ۲۰۰ میلی لیتری",
        Weight: "200 میلی لیتری",
        priceReduction: "",
        Discount: "",
        Price: "70,000",
        Brand: "کریستال",
        Seller: "هایپر استار",
        ProductFeatures: [
          {
            id: 79,
            type: " واکس",
            skinType: "انواع مو",
            effect: "صاف کننده مو برای انواع مو کوتاه و بلند",
            Durability: "بسیار قوی",
            dis: "فرم دهنده و تثبیت کننده رنگ مو",
          },
        ],
      },
      {
        id: 39,
        category: "آرایش مو",
        image: image39,
        title: "سرم تقویت کننده ابرو سینره ۶ میلی لیتری",
        Weight: "6 میلی لیتری",
        priceReduction: "107,000",
        Discount: "19%",
        Price: "86,670",
        Brand: "سینره",
        Seller: "هایپر استار",
        ProductFeatures: [
          {
            id: 80,
            type: " سرم",
            skinType: "انواع مو",
            effect: "محرک رویش و رشد مجدد ابرو",
            Durability: "بسیار قوی",
            dis: "تحریک گردش خون در محل و اکسیژن رسانی بهتر به ریشه ابروها",
          },
        ],
      },
      {
        id: 40,
        category: "آرایش مو",
        image: image40,
        title: "برس مو چوبی Medical رز",
        Weight: "",
        priceReduction: "",
        Discount: "",
        Price: "363,000",
        Brand: "رز",
        Seller: "هایپر استار",
        ProductFeatures: [{}],
      },
      {
        id: 41,
        category: "آرایش مو",
        image: image41,
        title: "اسپری نگهدارنده مو Extra Strong بیول ۲۵۰ میلی لیتری",
        Weight: "250 میلی لیتری",
        priceReduction: "45,100",
        Discount: "10%",
        Price: "40,590",
        Brand: "بیول",
        Seller: "هایپر استار",
        ProductFeatures: [
          {
            id: 81,
            type: " اسپری",
            skinType: "انواع مو",
            effect: "حجم دهنده مو",
            Durability: "بسیار قوی",
            dis: "دارای کراتین",
          },
        ],
      },
      {
        id: 42,
        category: "آرایش مو",
        image: image42,
        title: "ژل حالت دهنده مو Styling Freeze فولیکا ۱۵۰ میلی لیتری",
        Weight: "150 میلی لیتر",
        priceReduction: "",
        Discount: "",
        Price: "52,877",
        Brand: "فولیکا",
        Seller: "هایپر استار",
        ProductFeatures: [
          {
            id: 82,
            type: " ژل",
            skinType: "انواع مو",
            effect: "حاوی فیلتر جاذب اشعه ماورای بنفش نور خورشید",
            Durability: "بسیار قوی",
            dis: "فرمولاسیون شده با پروتئین گندم و سویا برای رفع رطوبت",
          },
        ],
      },
      {
        id: 43,
        category: "آرایش مو",
        image: image43,
        title: "ژل واکس مو تاپ شاپ ۲۰۰ میلی لیتری",
        Weight: "200 میلی لیتر",
        priceReduction: "",
        Discount: "",
        Price: "68,250",
        Brand: "",
        Seller: "",
        ProductFeatures: [
          {
            id: 83,
            type: " ژل",
            skinType: "انواع مو",
            effect: "بدون ایجاد سفیدی روی مو",
            Durability: "بسیار قوی",
            dis: "حاوی شی باتر",
          },
        ],
      },
      {
        id: 44,
        category: "آرایش مو",
        image: image44,
        title: "کیت رنگ مو بلوند مرواریدی شماره ۹.۲۲ زی فام",
        Weight: "50 میلی لیتر",
        priceReduction: "100,000",
        Discount: "25%",
        Price: "75,000",
        Brand: "زی فام",
        Seller: "هایپر استار",
        ProductFeatures: [
          {
            id: 84,
            type: " رنگ مو",
            skinType: "انواع مو",
            effect:
              "اکسیدان 75 میلی لیتر، سرم مو 5 میلی لیتر محافظت کننده هنگام رنگ، ماسک مو 20 میلی لیتر، ماسک تثبیت کننده رنگ مو، دستکش",
            Durability: "بسیار قوی",
            dis: "لطافت بخش و درخشان کننده موها بعد از رنگ",
          },
        ],
      },
    ],
  },
];
